/**
 * Theme tokens drive the CSS custom properties consumed by the client.
 * Presets are seeded into the Theme table; the Admin Console can edit them or
 * add a Custom theme. The client applies tokens as `--color-*` CSS variables
 * and re-applies live on the Socket.IO `theme:updated` event.
 */
export const THEME_TOKEN_KEYS = [
  'bg',
  'surface',
  'surface-raised',
  'surface-overlay',
  'border',
  'border-subtle',
  'text-primary',
  'text-secondary',
  'text-muted',
  'text-disabled',
  'accent',
  'accent-hover',
  'accent-muted',
  'accent-fg',
  'success',
  'success-muted',
  'warning',
  'warning-muted',
  'danger',
  'danger-muted',
  'info',
  'info-muted',
] as const;

export type ThemeTokenKey = (typeof THEME_TOKEN_KEYS)[number];
export type ThemeTokens = Record<ThemeTokenKey, string>;

export interface ThemePreset {
  name: string;
  isDefault?: boolean;
  tokens: ThemeTokens;
}

const lumen: ThemeTokens = {
  bg: '#f5f7fc',
  surface: '#ffffff',
  'surface-raised': '#f2f5fc',
  'surface-overlay': '#e9edfa',
  border: '#e4e8f3',
  'border-subtle': '#eef1f9',
  'text-primary': '#0f1729',
  'text-secondary': '#475069',
  'text-muted': '#8b94ab',
  'text-disabled': '#bcc4d6',
  accent: '#6366f1',
  'accent-hover': '#4f46e5',
  'accent-muted': '#eef0fe',
  'accent-fg': '#ffffff',
  success: '#059669',
  'success-muted': '#d1fae5',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#e11d48',
  'danger-muted': '#ffe4e6',
  info: '#0ea5e9',
  'info-muted': '#e0f2fe',
};

const midnight: ThemeTokens = {
  bg: '#0a0e1a',
  surface: '#111727',
  'surface-raised': '#1a2236',
  'surface-overlay': '#212a40',
  border: '#283046',
  'border-subtle': '#1c2438',
  'text-primary': '#f1f5fb',
  'text-secondary': '#aeb9cf',
  'text-muted': '#6b7794',
  'text-disabled': '#4a5468',
  accent: '#5b8cff',
  'accent-hover': '#7aa1ff',
  'accent-muted': '#1d2b52',
  'accent-fg': '#ffffff',
  success: '#34d399',
  'success-muted': '#0f3d31',
  warning: '#fbbf24',
  'warning-muted': '#3d310f',
  danger: '#f87171',
  'danger-muted': '#3d1717',
  info: '#60a5fa',
  'info-muted': '#16304d',
};

const slate: ThemeTokens = {
  bg: '#16181d',
  surface: '#1d2025',
  'surface-raised': '#26292f',
  'surface-overlay': '#2e3138',
  border: '#34383f',
  'border-subtle': '#26292f',
  'text-primary': '#f3f4f6',
  'text-secondary': '#b4b8bf',
  'text-muted': '#787d87',
  'text-disabled': '#52565e',
  accent: '#818cf8',
  'accent-hover': '#9aa3fa',
  'accent-muted': '#272a4a',
  'accent-fg': '#ffffff',
  success: '#4ade80',
  'success-muted': '#16341f',
  warning: '#facc15',
  'warning-muted': '#342c0d',
  danger: '#f87171',
  'danger-muted': '#34191a',
  info: '#38bdf8',
  'info-muted': '#0e2f40',
};

const arctic: ThemeTokens = {
  bg: '#f7f9fc',
  surface: '#ffffff',
  'surface-raised': '#ffffff',
  'surface-overlay': '#ffffff',
  border: '#e2e8f0',
  'border-subtle': '#eef2f7',
  'text-primary': '#0f172a',
  'text-secondary': '#475569',
  'text-muted': '#94a3b8',
  'text-disabled': '#cbd5e1',
  accent: '#3b6cf6',
  'accent-hover': '#2c5af0',
  'accent-muted': '#e4ecff',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#2563eb',
  'info-muted': '#dbeafe',
};

const obsidian: ThemeTokens = {
  bg: '#000000',
  surface: '#0a0a0a',
  'surface-raised': '#141414',
  'surface-overlay': '#1c1c1c',
  border: '#262626',
  'border-subtle': '#171717',
  'text-primary': '#fafafa',
  'text-secondary': '#a3a3a3',
  'text-muted': '#666666',
  'text-disabled': '#404040',
  accent: '#ffffff',
  'accent-hover': '#e5e5e5',
  'accent-muted': '#1f1f1f',
  'accent-fg': '#000000',
  success: '#22c55e',
  'success-muted': '#0a2a14',
  warning: '#eab308',
  'warning-muted': '#2a230a',
  danger: '#ef4444',
  'danger-muted': '#2a0f0f',
  info: '#3b82f6',
  'info-muted': '#0f1d33',
};

const sage: ThemeTokens = {
  bg: '#0e1512',
  surface: '#141d18',
  'surface-raised': '#1c2820',
  'surface-overlay': '#233029',
  border: '#2a382f',
  'border-subtle': '#1c2820',
  'text-primary': '#eef4ef',
  'text-secondary': '#a9bcb0',
  'text-muted': '#6c8074',
  'text-disabled': '#48584e',
  accent: '#4ade80',
  'accent-hover': '#6ee79b',
  'accent-muted': '#163524',
  'accent-fg': '#06140c',
  success: '#34d399',
  'success-muted': '#0f3d31',
  warning: '#fbbf24',
  'warning-muted': '#3a2f12',
  danger: '#f87171',
  'danger-muted': '#3a1a1a',
  info: '#5eead4',
  'info-muted': '#0e332e',
};

const daylight: ThemeTokens = {
  bg: '#f4f8fd',
  surface: '#ffffff',
  'surface-raised': '#f7fafe',
  'surface-overlay': '#eef5fd',
  border: '#dceaf6',
  'border-subtle': '#eaf2fb',
  'text-primary': '#0c1b2a',
  'text-secondary': '#3f5366',
  'text-muted': '#8499a9',
  'text-disabled': '#bcccd9',
  accent: '#0284c7',
  'accent-hover': '#0369a1',
  'accent-muted': '#e0f2fe',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#0ea5e9',
  'info-muted': '#e0f2fe',
};

const sandstone: ThemeTokens = {
  bg: '#faf6f0',
  surface: '#ffffff',
  'surface-raised': '#fdfaf5',
  'surface-overlay': '#f6efe4',
  border: '#ece2d4',
  'border-subtle': '#f4ece0',
  'text-primary': '#2a2018',
  'text-secondary': '#5c4f41',
  'text-muted': '#998a78',
  'text-disabled': '#cdc0af',
  accent: '#d97706',
  'accent-hover': '#b45309',
  'accent-muted': '#fef3c7',
  'accent-fg': '#ffffff',
  success: '#15803d',
  'success-muted': '#dcfce7',
  warning: '#ca8a04',
  'warning-muted': '#fef9c3',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#0891b2',
  'info-muted': '#cffafe',
};

const rose: ThemeTokens = {
  bg: '#fdf5f7',
  surface: '#ffffff',
  'surface-raised': '#fef7f9',
  'surface-overlay': '#fbeef2',
  border: '#f3dde4',
  'border-subtle': '#f9e9ee',
  'text-primary': '#2b1620',
  'text-secondary': '#5e4651',
  'text-muted': '#9c8089',
  'text-disabled': '#d6c2ca',
  accent: '#e11d48',
  'accent-hover': '#be123c',
  'accent-muted': '#ffe4e6',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#2563eb',
  'info-muted': '#dbeafe',
};

const meadow: ThemeTokens = {
  bg: '#f3f9f4',
  surface: '#ffffff',
  'surface-raised': '#f6fbf7',
  'surface-overlay': '#eaf6ed',
  border: '#d8ecdd',
  'border-subtle': '#e8f4ea',
  'text-primary': '#0f2417',
  'text-secondary': '#3c5446',
  'text-muted': '#7d9685',
  'text-disabled': '#b9cec0',
  accent: '#059669',
  'accent-hover': '#047857',
  'accent-muted': '#d1fae5',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#0d9488',
  'info-muted': '#ccfbf1',
};

const lavender: ThemeTokens = {
  bg: '#f7f5fd',
  surface: '#ffffff',
  'surface-raised': '#faf8fe',
  'surface-overlay': '#f1ecfb',
  border: '#e6def5',
  'border-subtle': '#efe9fa',
  'text-primary': '#1f1830',
  'text-secondary': '#4d4263',
  'text-muted': '#897e9f',
  'text-disabled': '#cabfde',
  accent: '#7c3aed',
  'accent-hover': '#6d28d9',
  'accent-muted': '#ede9fe',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#2563eb',
  'info-muted': '#dbeafe',
};

const blush: ThemeTokens = {
  bg: '#fdf4f8',
  surface: '#ffffff',
  'surface-raised': '#fef6fa',
  'surface-overlay': '#fbebf3',
  border: '#f4dbe7',
  'border-subtle': '#f9e8f0',
  'text-primary': '#2c1622',
  'text-secondary': '#604555',
  'text-muted': '#9e7e8d',
  'text-disabled': '#d8c1cd',
  accent: '#db2777',
  'accent-hover': '#be185d',
  'accent-muted': '#fce7f3',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#2563eb',
  'info-muted': '#dbeafe',
};

const coral: ThemeTokens = {
  bg: '#fff6f3',
  surface: '#ffffff',
  'surface-raised': '#fff8f5',
  'surface-overlay': '#ffeee7',
  border: '#ffdccf',
  'border-subtle': '#ffe7dd',
  'text-primary': '#2c1812',
  'text-secondary': '#5e463d',
  'text-muted': '#9c8076',
  'text-disabled': '#d6c2b9',
  accent: '#f15a40',
  'accent-hover': '#e0432a',
  'accent-muted': '#ffe2db',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#0ea5e9',
  'info-muted': '#e0f2fe',
};

const sky: ThemeTokens = {
  bg: '#f1f8fe',
  surface: '#ffffff',
  'surface-raised': '#f5fafe',
  'surface-overlay': '#e7f2fc',
  border: '#d3e7f6',
  'border-subtle': '#e4f0fb',
  'text-primary': '#0c1d2c',
  'text-secondary': '#3a5167',
  'text-muted': '#7993a8',
  'text-disabled': '#b6cad9',
  accent: '#0ea5e9',
  'accent-hover': '#0284c7',
  'accent-muted': '#e0f2fe',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#2563eb',
  'info-muted': '#dbeafe',
};

const mint: ThemeTokens = {
  bg: '#f0faf7',
  surface: '#ffffff',
  'surface-raised': '#f4fcf9',
  'surface-overlay': '#e6f6f0',
  border: '#d2ece2',
  'border-subtle': '#e4f4ec',
  'text-primary': '#0c211c',
  'text-secondary': '#3a544c',
  'text-muted': '#79968c',
  'text-disabled': '#b8d0c6',
  accent: '#14b8a6',
  'accent-hover': '#0d9488',
  'accent-muted': '#ccfbf1',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#0891b2',
  'info-muted': '#cffafe',
};

const amber: ThemeTokens = {
  bg: '#fffaf0',
  surface: '#ffffff',
  'surface-raised': '#fffcf5',
  'surface-overlay': '#fdf3e2',
  border: '#f4e6cd',
  'border-subtle': '#faf0dd',
  'text-primary': '#291f10',
  'text-secondary': '#574734',
  'text-muted': '#94806a',
  'text-disabled': '#cfbfa6',
  accent: '#f59e0b',
  'accent-hover': '#d97706',
  'accent-muted': '#fef3c7',
  'accent-fg': '#291f10',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#ca8a04',
  'warning-muted': '#fef9c3',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#0891b2',
  'info-muted': '#cffafe',
};

const grape: ThemeTokens = {
  bg: '#faf4fd',
  surface: '#ffffff',
  'surface-raised': '#fcf7fe',
  'surface-overlay': '#f5eafb',
  border: '#ecd9f4',
  'border-subtle': '#f3e6f9',
  'text-primary': '#260f30',
  'text-secondary': '#523a5e',
  'text-muted': '#8e759a',
  'text-disabled': '#cbb6d4',
  accent: '#9333ea',
  'accent-hover': '#7e22ce',
  'accent-muted': '#f3e8ff',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#2563eb',
  'info-muted': '#dbeafe',
};

const lime: ThemeTokens = {
  bg: '#f6faef',
  surface: '#ffffff',
  'surface-raised': '#f9fcf3',
  'surface-overlay': '#eef6e1',
  border: '#dcebc7',
  'border-subtle': '#eaf3da',
  'text-primary': '#1a2310',
  'text-secondary': '#475334',
  'text-muted': '#84946a',
  'text-disabled': '#c0cda6',
  accent: '#65a30d',
  'accent-hover': '#4d7c0f',
  'accent-muted': '#ecfccb',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#0891b2',
  'info-muted': '#cffafe',
};

const tangerine: ThemeTokens = {
  bg: '#fff7f0',
  surface: '#ffffff',
  'surface-raised': '#fffaf4',
  'surface-overlay': '#ffefe0',
  border: '#ffddc2',
  'border-subtle': '#ffe9d6',
  'text-primary': '#2b1709',
  'text-secondary': '#5c452f',
  'text-muted': '#9a7f64',
  'text-disabled': '#d4c0aa',
  accent: '#ea580c',
  'accent-hover': '#c2410c',
  'accent-muted': '#ffedd5',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#ca8a04',
  'warning-muted': '#fef9c3',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#0ea5e9',
  'info-muted': '#e0f2fe',
};

const fuchsia: ThemeTokens = {
  bg: '#fdf4fd',
  surface: '#ffffff',
  'surface-raised': '#fef6fe',
  'surface-overlay': '#fae9fb',
  border: '#f1d6f3',
  'border-subtle': '#f7e6f8',
  'text-primary': '#2b0f2c',
  'text-secondary': '#5a3a5b',
  'text-muted': '#977397',
  'text-disabled': '#d4b6d4',
  accent: '#c026d3',
  'accent-hover': '#a21caf',
  'accent-muted': '#fae8ff',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#2563eb',
  'info-muted': '#dbeafe',
};

const steel: ThemeTokens = {
  bg: '#f4f6f8',
  surface: '#ffffff',
  'surface-raised': '#f8fafc',
  'surface-overlay': '#eef2f6',
  border: '#dde4ec',
  'border-subtle': '#e9eef4',
  'text-primary': '#111a25',
  'text-secondary': '#3f4c5c',
  'text-muted': '#7c8a9b',
  'text-disabled': '#bcc7d3',
  accent: '#64748b',
  'accent-hover': '#475569',
  'accent-muted': '#e2e8f0',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#2563eb',
  'info-muted': '#dbeafe',
};

const ruby: ThemeTokens = {
  bg: '#fdf3f6',
  surface: '#ffffff',
  'surface-raised': '#fef5f8',
  'surface-overlay': '#fbe9ee',
  border: '#f3d4dd',
  'border-subtle': '#f9e3ea',
  'text-primary': '#2a0c16',
  'text-secondary': '#583541',
  'text-muted': '#977079',
  'text-disabled': '#d4b4bd',
  accent: '#9f1239',
  'accent-hover': '#881337',
  'accent-muted': '#ffe4e9',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#2563eb',
  'info-muted': '#dbeafe',
};

const marigold: ThemeTokens = {
  bg: '#fdfbef',
  surface: '#ffffff',
  'surface-raised': '#fffdf4',
  'surface-overlay': '#fbf6df',
  border: '#efe5c2',
  'border-subtle': '#f7efd6',
  'text-primary': '#241e08',
  'text-secondary': '#524829',
  'text-muted': '#8f825c',
  'text-disabled': '#cdc197',
  accent: '#ca8a04',
  'accent-hover': '#a16207',
  'accent-muted': '#fef9c3',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#ca8a04',
  'warning-muted': '#fef9c3',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#0891b2',
  'info-muted': '#cffafe',
};

const cocoa: ThemeTokens = {
  bg: '#fbf6f1',
  surface: '#ffffff',
  'surface-raised': '#fdf9f4',
  'surface-overlay': '#f6ebe0',
  border: '#e9d9c9',
  'border-subtle': '#f2e6d9',
  'text-primary': '#291810',
  'text-secondary': '#574234',
  'text-muted': '#937c6b',
  'text-disabled': '#cdbaa9',
  accent: '#92400e',
  'accent-hover': '#7c2d12',
  'accent-muted': '#f5e6d8',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#ca8a04',
  'warning-muted': '#fef9c3',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#0891b2',
  'info-muted': '#cffafe',
};

const forest: ThemeTokens = {
  bg: '#f1f8f3',
  surface: '#ffffff',
  'surface-raised': '#f5fbf6',
  'surface-overlay': '#e6f3ea',
  border: '#d2e9d9',
  'border-subtle': '#e4f1e8',
  'text-primary': '#0c2114',
  'text-secondary': '#37503f',
  'text-muted': '#73917f',
  'text-disabled': '#b1ccba',
  accent: '#166534',
  'accent-hover': '#14532d',
  'accent-muted': '#d1f0db',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#0d9488',
  'info-muted': '#ccfbf1',
};

const pine: ThemeTokens = {
  bg: '#eff9f7',
  surface: '#ffffff',
  'surface-raised': '#f4fbfa',
  'surface-overlay': '#e2f3f0',
  border: '#cde9e4',
  'border-subtle': '#dff2ee',
  'text-primary': '#08211e',
  'text-secondary': '#345049',
  'text-muted': '#6f9189',
  'text-disabled': '#adccc5',
  accent: '#0f766e',
  'accent-hover': '#115e59',
  'accent-muted': '#ccf2ec',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#0891b2',
  'info-muted': '#cffafe',
};

const plum: ThemeTokens = {
  bg: '#fcf2fd',
  surface: '#ffffff',
  'surface-raised': '#fdf5fe',
  'surface-overlay': '#f7e6f9',
  border: '#eed3f1',
  'border-subtle': '#f5e3f7',
  'text-primary': '#28092b',
  'text-secondary': '#543656',
  'text-muted': '#917190',
  'text-disabled': '#d0b3d1',
  accent: '#86198f',
  'accent-hover': '#701a75',
  'accent-muted': '#f7daf9',
  'accent-fg': '#ffffff',
  success: '#16a34a',
  'success-muted': '#dcfce7',
  warning: '#d97706',
  'warning-muted': '#fef3c7',
  danger: '#dc2626',
  'danger-muted': '#fee2e2',
  info: '#2563eb',
  'info-muted': '#dbeafe',
};

export const THEME_PRESETS: ThemePreset[] = [
  // Light themes
  { name: 'Lumen', tokens: lumen },
  { name: 'Arctic', isDefault: true, tokens: arctic },
  { name: 'Daylight', tokens: daylight },
  { name: 'Sandstone', tokens: sandstone },
  { name: 'Rose', tokens: rose },
  { name: 'Ruby', tokens: ruby },
  { name: 'Blush', tokens: blush },
  { name: 'Coral', tokens: coral },
  { name: 'Tangerine', tokens: tangerine },
  { name: 'Cocoa', tokens: cocoa },
  { name: 'Amber', tokens: amber },
  { name: 'Marigold', tokens: marigold },
  { name: 'Lime', tokens: lime },
  { name: 'Forest', tokens: forest },
  { name: 'Meadow', tokens: meadow },
  { name: 'Mint', tokens: mint },
  { name: 'Pine', tokens: pine },
  { name: 'Sky', tokens: sky },
  { name: 'Lavender', tokens: lavender },
  { name: 'Grape', tokens: grape },
  { name: 'Plum', tokens: plum },
  { name: 'Fuchsia', tokens: fuchsia },
  { name: 'Steel', tokens: steel },
  // Dark themes
  { name: 'Midnight', tokens: midnight },
  { name: 'Slate', tokens: slate },
  { name: 'Obsidian', tokens: obsidian },
  { name: 'Sage', tokens: sage },
];

export const DEFAULT_THEME = THEME_PRESETS.find((t) => t.isDefault) ?? THEME_PRESETS[0];
