export interface EnterpriseCsvColumn<T> {
  header: string;
  key: keyof T | ((row: T) => any);
}

export interface EnterpriseCsvConfig<T> {
  title: string;
  description: string;
  generatedBy: string;
  environment: string; // e.g. "Production"
  totalRecords: number;
  filters: Record<string, any>;
  filterNames: Record<string, string>; // Maps filter keys to human-readable names
  summary?: Record<string, string | number | null | undefined>;
  data: T[];
  columns: EnterpriseCsvColumn<T>[];
}

export function formatEnterpriseDate(date: Date | string | null | undefined): string {
  if (!date) return '-';
  const d = new Date(date);
  if (isNaN(d.getTime())) return '-';
  
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const dd = String(d.getDate()).padStart(2, '0');
  const mmm = months[d.getMonth()];
  const yyyy = d.getFullYear();
  const hh = String(d.getHours()).padStart(2, '0');
  const mm = String(d.getMinutes()).padStart(2, '0');
  const ss = String(d.getSeconds()).padStart(2, '0');
  
  return `${dd}-${mmm}-${yyyy} ${hh}:${mm}:${ss}`;
}

export function formatDuration(seconds: number | null | undefined): string {
  if (seconds == null || isNaN(seconds)) return '-';
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  return [h, m, s].map(v => String(v).padStart(2, '0')).join(':');
}

export function csvEscape(v: any): string {
  if (v == null || v === '') return '-';
  const s = String(v);
  if (/[",\r\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export class EnterpriseCsvBuilder {
  static generate<T>(config: EnterpriseCsvConfig<T>): string {
    const lines: string[] = [];
    
    // SECTION 1: Report Header
    lines.push('AgnoHire');
    lines.push(csvEscape(config.title));
    lines.push(csvEscape(config.description));
    lines.push('');
    lines.push(`Generated By :,${csvEscape(config.generatedBy)}`);
    lines.push(`Generated On :,${csvEscape(formatEnterpriseDate(new Date()))}`);
    lines.push(`Environment :,${csvEscape(config.environment)}`);
    lines.push(`Records Exported :,${config.totalRecords}`);
    lines.push(`Export Format :,CSV`);
    
    const filterCount = Object.keys(config.filterNames).length;
    lines.push(`Total Filters Applied :,${filterCount}`);
    lines.push('');
    lines.push('-'.repeat(60));
    lines.push('');

    // SECTION 2: Applied Filters
    lines.push('Applied Filters');
    lines.push('');
    for (const [key, label] of Object.entries(config.filterNames)) {
      const val = config.filters[key];
      let displayVal = 'All'; // Default for unselected
      
      if (val !== undefined && val !== null && val !== '') {
        if (Array.isArray(val)) {
           displayVal = val.length > 0 ? val.join(' | ') : 'All';
        } else if (val instanceof Date) {
           displayVal = formatEnterpriseDate(val);
        } else if (typeof val === 'object') {
           displayVal = JSON.stringify(val);
        } else {
           displayVal = String(val);
        }
      }
      lines.push(`${csvEscape(label)} :,${csvEscape(displayVal)}`);
    }
    lines.push('');
    lines.push('-'.repeat(60));
    lines.push('');

    // SECTION 3: Report Summary
    if (config.summary && Object.keys(config.summary).length > 0) {
      lines.push('Summary');
      lines.push('');
      for (const [key, val] of Object.entries(config.summary)) {
        if (val !== undefined && val !== null) {
           lines.push(`${csvEscape(key)},${csvEscape(val)}`);
        }
      }
      lines.push('');
      lines.push('-'.repeat(60));
      lines.push('');
    }

    // SECTION 4: Exported Data
    const headers = config.columns.map(c => csvEscape(c.header));
    lines.push(headers.join(','));
    
    for (const row of config.data) {
      const rowArr = config.columns.map(c => {
        let val;
        if (typeof c.key === 'function') {
           val = (c.key as any)(row);
        } else {
           val = row[c.key as keyof T];
        }
        return csvEscape(val);
      });
      lines.push(rowArr.join(','));
    }
    lines.push('');
    lines.push('');

    // SECTION 5: Footer
    lines.push('-'.repeat(52));
    lines.push('End of Report');
    lines.push('Generated by AgnoHire Reporting System');
    lines.push('');
    lines.push('This report is system generated and does not require a signature.');
    lines.push('-'.repeat(52));
    
    return lines.join('\r\n');
  }
}
