import ExcelJS from 'exceljs';

export interface EnterpriseExcelColumn<T> {
  header: string;
  key: keyof T | ((row: T) => any);
}

export interface EnterpriseExcelConfig<T> {
  title: string;
  description: string;
  generatedBy: string;
  environment: string; 
  totalRecords: number;
  filters: Record<string, any>;
  filterNames: Record<string, string>; 
  summary?: Record<string, string | number | null | undefined>;
  data: T[];
  columns: EnterpriseExcelColumn<T>[];
}

export function formatEnterpriseDate(date: Date | string | null | undefined): string {
  if (!date) return '-';
  const d = new Date(date);
  if (isNaN(d.getTime())) return '-';
  
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const dd = String(d.getDate()).padStart(2, '0');
  const mmm = months[d.getMonth()];
  const yyyy = d.getFullYear();
  const hh = String(d.getHours()).padStart(2, '0');
  const mm = String(d.getMinutes()).padStart(2, '0');
  const ss = String(d.getSeconds()).padStart(2, '0');
  
  return `${dd}-${mmm}-${yyyy} ${hh}:${mm}:${ss}`;
}

export class EnterpriseExcelBuilder {
  static async generate<T>(config: EnterpriseExcelConfig<T>): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'AgnoHire Reporting System';
    const sheet = workbook.addWorksheet('Report');

    const styleHeaderRow = (rowNumber: number, bgColor: string, fontColor: string = 'FFFFFF') => {
      const row = sheet.getRow(rowNumber);
      // We apply it across standard columns to make the bar look complete
      for (let i = 1; i <= Math.max(10, config.columns.length); i++) {
        const cell = row.getCell(i);
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: bgColor }
        };
        cell.font = { bold: true, color: { argb: fontColor } };
      }
    };

    let currentRow = 1;

    // SECTION 1: Report Header
    sheet.getCell(`A${currentRow}`).value = 'AgnoHire';
    sheet.getCell(`A${currentRow}`).font = { bold: true, size: 14 };
    currentRow++;

    sheet.getCell(`A${currentRow}`).value = config.title;
    sheet.getCell(`A${currentRow}`).font = { bold: true };
    currentRow++;

    sheet.getCell(`A${currentRow}`).value = config.description;
    currentRow += 2;

    sheet.getCell(`A${currentRow}`).value = 'Generated By :';
    sheet.getCell(`B${currentRow}`).value = config.generatedBy;
    currentRow++;

    sheet.getCell(`A${currentRow}`).value = 'Generated On :';
    sheet.getCell(`B${currentRow}`).value = formatEnterpriseDate(new Date());
    currentRow++;

    sheet.getCell(`A${currentRow}`).value = 'Environment :';
    sheet.getCell(`B${currentRow}`).value = config.environment;
    currentRow++;

    sheet.getCell(`A${currentRow}`).value = 'Records Exported :';
    sheet.getCell(`B${currentRow}`).value = config.totalRecords;
    currentRow++;

    sheet.getCell(`A${currentRow}`).value = 'Export Format :';
    sheet.getCell(`B${currentRow}`).value = 'Excel (.xlsx)';
    currentRow++;

    sheet.getCell(`A${currentRow}`).value = 'Total Filters Applied :';
    sheet.getCell(`B${currentRow}`).value = Object.keys(config.filterNames).length;
    currentRow += 2;

    // SECTION 2: Applied Filters
    sheet.getCell(`A${currentRow}`).value = 'Applied Filters';
    styleHeaderRow(currentRow, 'FF203764'); // Dark Blue
    currentRow++;

    for (const [key, label] of Object.entries(config.filterNames)) {
      const val = config.filters[key];
      let displayVal = 'All';
      
      if (val !== undefined && val !== null && val !== '') {
        if (Array.isArray(val)) {
           displayVal = val.length > 0 ? val.join(' | ') : 'All';
        } else if (val instanceof Date) {
           displayVal = formatEnterpriseDate(val);
        } else if (typeof val === 'object') {
           displayVal = JSON.stringify(val);
        } else {
           displayVal = String(val);
        }
      }
      sheet.getCell(`A${currentRow}`).value = label + ' :';
      sheet.getCell(`B${currentRow}`).value = displayVal;
      currentRow++;
    }
    currentRow++;

    // SECTION 3: Report Summary
    if (config.summary && Object.keys(config.summary).length > 0) {
      sheet.getCell(`A${currentRow}`).value = 'Summary';
      styleHeaderRow(currentRow, 'FF00B050'); // Green
      currentRow++;
      
      for (const [key, val] of Object.entries(config.summary)) {
        if (val !== undefined && val !== null) {
          sheet.getCell(`A${currentRow}`).value = key;
          sheet.getCell(`B${currentRow}`).value = val;
          currentRow++;
        }
      }
      currentRow++;
    }

    // SECTION 4: Exported Data
    const headerRow = sheet.getRow(currentRow);
    config.columns.forEach((c, idx) => {
      headerRow.getCell(idx + 1).value = c.header;
    });
    styleHeaderRow(currentRow, 'FF44546A'); // Gray-blue
    currentRow++;

    for (const rowData of config.data) {
      const dataRow = sheet.getRow(currentRow);
      config.columns.forEach((c, idx) => {
        let val;
        if (typeof c.key === 'function') {
           val = (c.key as any)(rowData);
        } else {
           val = rowData[c.key as keyof T];
        }
        dataRow.getCell(idx + 1).value = val == null || val === '' ? '-' : val;
      });
      currentRow++;
    }
    currentRow++;

    // SECTION 5: Footer
    sheet.getCell(`A${currentRow}`).value = 'End of Report';
    sheet.getCell(`A${currentRow}`).font = { bold: true };
    currentRow++;
    sheet.getCell(`A${currentRow}`).value = 'Generated by AgnoHire Reporting System';
    currentRow++;
    sheet.getCell(`A${currentRow}`).value = 'This report is system generated and does not require a signature.';
    
    // Auto-size columns for A and B at minimum
    sheet.columns.forEach((column) => {
      let maxLen = 12;
      column.eachCell!({ includeEmpty: false }, (cell) => {
        const len = cell.value ? cell.value.toString().length : 0;
        if (len > maxLen) maxLen = len;
      });
      column.width = Math.min(maxLen + 2, 50);
    });

    const buffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(buffer);
  }
}
