import type { Request, Response } from 'express';
import { ok } from '../utils/response.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import {
  createPlanSchema,
  updatePlanSchema,
  createTenantSchema,
  tenantStatusSchema,
  updateTenantSchema,
  createMaintenanceWindowSchema,
  adminResetPasswordSchema,
  setTenantCareersFeatureSchema,
} from '@agnohire/shared';
import * as planAdmin from '../services/planAdminService.js';
import * as tenantAdmin from '../services/tenantAdminService.js';
import * as maintenanceAdmin from '../services/maintenanceService.js';
import { createTenantByAdmin } from '../services/tenantProvisioningService.js';
import { loginByUserId } from '../services/authService.js';
import { runAsPlatform } from '../config/tenantContext.js';
import { setRefreshCookie } from './auth.controller.js';
import { recordAudit } from '../services/auditService.js';
import * as aiUsage from '../services/aiUsageAggregationService.js';
import * as candidateStorage from '../services/candidateStorageService.js';
import { prisma } from '../config/database.js';

/** Full name of the requesting superadmin, for the "Generated by" line on exported reports. */
async function requesterName(req: Request): Promise<string> {
  const user = await prisma.user.findUnique({ where: { id: req.user!.sub }, select: { fullName: true } });
  return user?.fullName ?? 'Superadmin';
}

function parseRangeDays(req: Request): number {
  const raw = Number(req.query.days);
  if (!Number.isFinite(raw) || raw <= 0) return 30;
  return Math.min(Math.round(raw), 365);
}

// ── Plans ─────────────────────────────────────────────────────────────────────
export const listPlans = asyncHandler(async (_req: Request, res: Response) => {
  return ok(res, await planAdmin.listPlans());
});

export const createPlan = asyncHandler(async (req: Request, res: Response) => {
  const plan = await planAdmin.createPlan(createPlanSchema.parse(req.body));
  await recordAudit(req, { action: 'PLAN_CREATE', entity: 'Plan', entityId: plan.id, description: `Created plan ${plan.code}` });
  return ok(res, plan, 201);
});

export const updatePlan = asyncHandler(async (req: Request, res: Response) => {
  const plan = await planAdmin.updatePlan(req.params.id, updatePlanSchema.parse(req.body));
  await recordAudit(req, { action: 'PLAN_UPDATE', entity: 'Plan', entityId: plan.id, description: `Updated plan ${plan.code}` });
  return ok(res, plan);
});

// ── Tenants ────────────────────────────────────────────────────────
export const listTenants = asyncHandler(async (req: Request, res: Response) => {
  return ok(res, await tenantAdmin.listTenants(req.user!.sub));
});

export const getTenant = asyncHandler(async (req: Request, res: Response) => {
  return ok(res, await tenantAdmin.getTenant(req.params.id, req.user!.sub));
});

export const createTenant = asyncHandler(async (req: Request, res: Response) => {
  const result = await createTenantByAdmin(createTenantSchema.parse(req.body), req.user!.sub);
  await recordAudit(req, {
    action: 'WORKSPACE_CREATE',
    entity: 'Tenant',
    entityId: result.tenantId,
    description: `Provisioned workspace ${result.slug} for ${result.ownerEmail}`,
  });
  return ok(res, result, 201);
});

export const updateTenant = asyncHandler(async (req: Request, res: Response) => {
  const tenant = await tenantAdmin.updateTenant(req.params.id, updateTenantSchema.parse(req.body), req.user!.sub);
  await recordAudit(req, {
    action: 'WORKSPACE_UPDATE',
    entity: 'Tenant',
    entityId: req.params.id,
    description: `Updated workspace ${tenant.slug}`,
  });
  return ok(res, tenant);
});

/**
 * Impersonate (sign into) a tenant the operator created. Mints a full session
 * for the tenant owner and swaps the refresh cookie to it, so the SPA becomes
 * that owner. Restricted to the creating operator.
 */
export const tenantLogin = asyncHandler(async (req: Request, res: Response) => {
  const ownerUserId = await tenantAdmin.assertCreatedByAndGetOwner(req.params.id, req.user!.sub);
  // The owner lives in another tenant, so mint their session under a platform
  // bypass — the operator's own tenant scope would otherwise hide the user.
  // This is the one path allowed to skip the tenant-approval gate, so an
  // operator can enter a tenant they are still reviewing. The flag is
  // persisted on the refresh token, so the exemption survives rotation (the SPA
  // re-bootstraps through /refresh) without exempting anybody else.
  const tokens = await runAsPlatform(() =>
    loginByUserId(ownerUserId, req, { impersonated: true }),
  );
  await recordAudit(req, {
    action: 'WORKSPACE_IMPERSONATE',
    entity: 'Tenant',
    entityId: req.params.id,
    description: `Signed in as workspace owner ${tokens.user.email}`,
  });
  setRefreshCookie(res, tokens.refreshToken, tokens.refreshExpiresAt);
  return ok(res, { accessToken: tokens.accessToken, user: tokens.user });
});

export const resetOwnerPassword = asyncHandler(async (req: Request, res: Response) => {
  const { password } = adminResetPasswordSchema.parse(req.body);
  await tenantAdmin.resetOwnerPassword(req.params.id, password, req.user!.sub);
  await recordAudit(req, {
    action: 'WORKSPACE_UPDATE',
    entity: 'Tenant',
    entityId: req.params.id,
    description: 'Reset workspace owner password',
  });
  return ok(res, { reset: true });
});

export const setTenantStatus = asyncHandler(async (req: Request, res: Response) => {
  const { status } = tenantStatusSchema.parse(req.body);
  await tenantAdmin.setTenantStatus(req.params.id, status);
  await recordAudit(req, {
    action: status === 'SUSPENDED' ? 'WORKSPACE_SUSPEND' : 'WORKSPACE_ACTIVATE',
    entity: 'Tenant',
    entityId: req.params.id,
    description: `Workspace ${status === 'SUSPENDED' ? 'suspended' : 'reactivated'}`,
  });
  return ok(res, { status });
});

export const setCareersFeature = asyncHandler(async (req: Request, res: Response) => {
  const { enabled } = setTenantCareersFeatureSchema.parse(req.body);
  await tenantAdmin.setCareersPageEnabled(req.params.id, enabled);
  await recordAudit(req, {
    action: enabled ? 'WORKSPACE_CAREERS_FEATURE_GRANT' : 'WORKSPACE_CAREERS_FEATURE_REVOKE',
    entity: 'Tenant',
    entityId: req.params.id,
    description: `Careers page feature ${enabled ? 'granted to' : 'revoked from'} workspace`,
  });
  return ok(res, { careersPageEnabled: enabled });
});

export const approveTenant = asyncHandler(async (req: Request, res: Response) => {
  const { tenantApprovalSchema } = await import('@agnohire/shared');
  const { notes } = tenantApprovalSchema.parse(req.body ?? {});
  const tenant = await tenantAdmin.approveTenant(req.params.id, notes, req.user!.sub);
  await recordAudit(req, {
    action: 'WORKSPACE_APPROVE',
    entity: 'Tenant',
    entityId: req.params.id,
    description: `Approved workspace ${tenant.slug}${notes ? ` (${notes})` : ''}`,
  });
  return ok(res, tenant);
});

export const rejectTenant = asyncHandler(async (req: Request, res: Response) => {
  const { tenantApprovalSchema } = await import('@agnohire/shared');
  const { notes } = tenantApprovalSchema.parse(req.body ?? {});
  await tenantAdmin.rejectTenant(req.params.id, notes, req.user!.sub);
  await recordAudit(req, {
    action: 'WORKSPACE_REJECT',
    entity: 'Tenant',
    entityId: req.params.id,
    description: `Rejected workspace${notes ? ` (${notes})` : ''}`,
  });
  return ok(res, { rejected: true });
});

export const deleteTenant = asyncHandler(async (req: Request, res: Response) => {
  await tenantAdmin.deleteTenant(req.params.id);
  await recordAudit(req, {
    action: 'WORKSPACE_DELETE',
    entity: 'Tenant',
    entityId: req.params.id,
    description: 'Workspace deleted (soft)',
  });
  return ok(res, { deleted: true });
});

// ── Maintenance windows ─────────────────────────────────────────────────────────
export const listMaintenanceWindows = asyncHandler(async (_req: Request, res: Response) => {
  return ok(res, await maintenanceAdmin.listMaintenanceWindows());
});

export const createMaintenanceWindow = asyncHandler(async (req: Request, res: Response) => {
  const window = await maintenanceAdmin.createMaintenanceWindow(createMaintenanceWindowSchema.parse(req.body), req.user!.sub);
  await recordAudit(req, {
    action: 'MAINTENANCE_SCHEDULE',
    entity: 'MaintenanceWindow',
    entityId: window.id,
    description: `Scheduled maintenance "${window.title}"`,
  });
  return ok(res, window, 201);
});

export const cancelMaintenanceWindow = asyncHandler(async (req: Request, res: Response) => {
  await maintenanceAdmin.cancelMaintenanceWindow(req.params.id);
  await recordAudit(req, {
    action: 'MAINTENANCE_CANCEL',
    entity: 'MaintenanceWindow',
    entityId: req.params.id,
    description: 'Maintenance window cancelled',
  });
  return ok(res, { cancelled: true });
});

// ── AI usage monitor ────────────────────────────────────────────────────────
export const getAiUsageSummary = asyncHandler(async (req: Request, res: Response) => {
  return ok(res, await aiUsage.getUsageSummary(parseRangeDays(req)));
});

export const getAiUsageTrend = asyncHandler(async (req: Request, res: Response) => {
  return ok(res, await aiUsage.getUsageTrend(parseRangeDays(req)));
});

export const getAiUsageByTenant = asyncHandler(async (req: Request, res: Response) => {
  return ok(res, await aiUsage.getUsageByTenant(parseRangeDays(req)));
});

export const getAiUsageByFeature = asyncHandler(async (req: Request, res: Response) => {
  return ok(res, await aiUsage.getUsageByFeature(parseRangeDays(req)));
});

export const getAiUsageByModel = asyncHandler(async (req: Request, res: Response) => {
  return ok(res, await aiUsage.getUsageByModel(parseRangeDays(req)));
});

export const getTenantAiUsage = asyncHandler(async (req: Request, res: Response) => {
  return ok(res, await aiUsage.getTenantAiUsage(req.params.id, parseRangeDays(req)));
});

export const exportAiUsagePdf = asyncHandler(async (req: Request, res: Response) => {
  const days = parseRangeDays(req);
  const [summary, byTenant, byFeature, byModel] = await Promise.all([
    aiUsage.getUsageSummary(days),
    aiUsage.getUsageByTenant(days),
    aiUsage.getUsageByFeature(days),
    aiUsage.getUsageByModel(days),
  ]);
  const { generateAiUsagePDF } = await import('../services/pdfReportService.js');
  const { buffer, filename } = await generateAiUsagePDF({ summary, byTenant, byFeature, byModel }, days, await requesterName(req));
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.send(buffer);
});

// ── Candidate storage monitor ───────────────────────────────────────────────
export const getStorageSummary = asyncHandler(async (_req: Request, res: Response) => {
  return ok(res, await candidateStorage.getPlatformStorageSummary());
});

export const getStorageByTenant = asyncHandler(async (_req: Request, res: Response) => {
  return ok(res, await candidateStorage.getStorageByTenant());
});

export const exportStorageUsagePdf = asyncHandler(async (req: Request, res: Response) => {
  const [summary, byTenant] = await Promise.all([
    candidateStorage.getPlatformStorageSummary(),
    candidateStorage.getStorageByTenant(),
  ]);
  const { generateStorageUsagePDF } = await import('../services/pdfReportService.js');
  const { buffer, filename } = await generateStorageUsagePDF({ summary, byTenant }, await requesterName(req));
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.send(buffer);
});

export const getTenantStorageUsage = asyncHandler(async (req: Request, res: Response) => {
  return ok(res, await candidateStorage.getTenantStorageUsage(req.params.id));
});
