import PDFDocument from 'pdfkit';
import type { Prisma } from '@prisma/client';
import { prisma } from '../config/database.js';
import { NotFoundError } from '../utils/errors.js';
import { resolveTenantTimezone } from '../utils/tenantTimezone.js';
import type { AnalyticsDashboard } from '@agnohire/shared';
import type { UsageSummary, UsageByTenant, UsageByFeature, UsageByModel } from './aiUsageAggregationService.js';
import type { PlatformStorageSummary, TenantStorageBreakdown } from './candidateStorageService.js';

const INTERVIEW_REPORT_INCLUDE = {
  candidate: {
    include: {
      applications: {
        where: { deletedAt: null },
        include: { job: true },
        take: 1,
      },
    },
  },
  result: true,
  answers: { include: { question: true } },
  proctorShots: true,
  _count: {
    select: { questions: true },
  },
} as const;

type ReportableInterview = Prisma.InterviewGetPayload<{ include: typeof INTERVIEW_REPORT_INCLUDE }>;

/** Renders one candidate's report onto the given (already-open) PDF document. */

/** Renders one candidate's report onto the given (already-open) PDF document. */
function renderInterviewReport(doc: PDFKit.PDFDocument, interview: ReportableInterview, timezone: string, generatedBy: string): void {
  const result = interview.result!;

  const pageWidth = doc.page.width;
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;

  // ─── Shared Colors ───
  const colors = {
    primary: '#0f172a',
    secondary: '#1e293b',
    text: '#475569',
    light: '#64748b',
    border: '#e2e8f0',
    bg: '#f8fafc',
    white: '#ffffff',
    success: '#16a34a',
    error: '#dc2626',
    warning: '#d97706',
    successBg: '#dcfce7',
    errorBg: '#fee2e2',
    warningBg: '#fef3c7'
  };

  // ─── Header ───
  doc.rect(0, 0, pageWidth, 120).fill(colors.primary);
  
  // AgnoHire Logo Text
  doc.fontSize(32).font('Helvetica-Bold').fillColor(colors.white).text('AgnoHire', margin, 40);
  doc.fontSize(14).font('Helvetica').fillColor('#94a3b8').text('Interview Performance Report', margin, 75);
  doc.fontSize(10).font('Helvetica').fillColor('#94a3b8').text(`Generated by: ${generatedBy}`, margin, 95);

  // Right Aligned Header Text
  const rightTextX = pageWidth - margin - 200;
  const generatedStr = new Date().toLocaleString('en-GB', { timeZone: timezone });
  doc.fontSize(10).font('Helvetica').fillColor('#94a3b8').text('Confidential', rightTextX, 45, { width: 200, align: 'right' });
  doc.fontSize(9).text(`Date: ${generatedStr}`, rightTextX, 60, { width: 200, align: 'right' });
  doc.fontSize(9).text(`ID: ${interview.id.substring(0, 8).toUpperCase()}`, rightTextX, 73, { width: 200, align: 'right' });

  let currentY = 150;

  // ─── Helper function for section titles ───
  const addSectionTitle = (title: string, yPos: number, spacing = 25) => {
    if (yPos > doc.page.height - 120) { doc.addPage(); yPos = 40; }
    doc.fontSize(16).font('Helvetica-Bold').fillColor(colors.primary).text(title, margin, yPos);
    return yPos + spacing;
  };

  // ─── Candidate Summary Card ───
  currentY = addSectionTitle('Candidate Summary', currentY, 20);
  
  const cardHeight = 85;
  doc.roundedRect(margin, currentY, contentWidth, cardHeight, 6).fill(colors.bg).strokeColor(colors.border).lineWidth(1).stroke();

  const position = interview.candidate.applications?.[0]?.job?.title ?? 'General Position';
  const dateStr = interview.completedAt?.toLocaleDateString('en-GB', { timeZone: timezone, year: 'numeric', month: 'short', day: 'numeric' }) ?? 'N/A';
  const durationStr = interview.duration ? `${Math.round(interview.duration / 60)} mins` : 'N/A';
  
  const col1X = margin + 20;
  const col2X = margin + (contentWidth / 2) + 10;
  
  let cY = currentY + 15;
  
  const drawPair = (l1: string, v1: string, l2: string, v2: string, y: number) => {
    doc.fontSize(10).font('Helvetica').fillColor(colors.light).text(l1, col1X, y);
    doc.font('Helvetica-Bold').fillColor(colors.secondary).text(v1, col1X + 80, y);
    doc.font('Helvetica').fillColor(colors.light).text(l2, col2X, y);
    doc.font('Helvetica-Bold').fillColor(colors.secondary).text(v2, col2X + 80, y);
  };

  drawPair('Candidate:', interview.candidate.fullName, 'Role:', position, cY);
  cY += 20;
  drawPair('Date:', dateStr, 'Duration:', durationStr, cY);
  cY += 20;
  drawPair('Round:', interview.roundNumber ? String(interview.roundNumber) : '1', 'Type:', interview.type || 'AI', cY);

  currentY += cardHeight + 25;

  // ─── Assessment Overview ───
  currentY = addSectionTitle('Assessment Overview', currentY, 20);
  
  const decision = result.decision ?? result.aiDecision ?? 'Pending';
  const isPass = decision.toLowerCase() === 'pass';
  const isFail = decision.toLowerCase() === 'fail';
  const decColor = isPass ? colors.success : (isFail ? colors.error : colors.warning);
  const decBg = isPass ? colors.successBg : (isFail ? colors.errorBg : colors.warningBg);

  let totalQuestions = interview._count?.questions || 0;
  let correctAnswers = 0;
  let partialAnswers = 0;
  let wrongAnswers = 0;
  
  if (interview.answers) {
    totalQuestions = Math.max(totalQuestions, interview.answers.length);
    interview.answers.forEach(a => {
      if (a.isCorrect === true) correctAnswers++;
      else if (a.isCorrect === false) wrongAnswers++;
      else partialAnswers++;
    });
  }

  // Draw 4 cards in a row
  const cardW = (contentWidth - 45) / 4;
  let cardX = margin;
  
  const drawStatCard = (title: string, value: string, badgeBg?: string, badgeColor?: string) => {
    doc.roundedRect(cardX, currentY, cardW, 60, 6).fill(colors.white).strokeColor(colors.border).lineWidth(1).stroke();
    doc.fontSize(10).font('Helvetica').fillColor(colors.light).text(title, cardX, currentY + 12, { width: cardW, align: 'center' });
    
    if (badgeBg && badgeColor) {
      doc.roundedRect(cardX + cardW/2 - 30, currentY + 30, 60, 20, 10).fill(badgeBg);
      doc.fontSize(10).font('Helvetica-Bold').fillColor(badgeColor).text(value, cardX, currentY + 35, { width: cardW, align: 'center' });
    } else {
      doc.fontSize(16).font('Helvetica-Bold').fillColor(colors.primary).text(value, cardX, currentY + 32, { width: cardW, align: 'center' });
    }
    cardX += cardW + 15;
  };

  drawStatCard('Overall Score', `${result.percentageScore ?? 0}%`);
  drawStatCard('Decision', decision.toUpperCase(), decBg, decColor);
  drawStatCard('Q&A Score', `${correctAnswers}/${totalQuestions}`);
  
  let intScore = 100;
  if (interview.violations && Array.isArray(interview.violations)) {
    interview.violations.forEach((v: any) => {
      if (v.type === 'MULTIPLE_FACES' || v.type === 'MOBILE_PHONE') intScore -= 20;
      else if (v.type === 'MULTIPLE_VOICES' || v.type === 'UNUSUAL_NOISE' || v.type === 'SUSPICIOUS_OBJECT') intScore -= 15;
      else if (v.type === 'COPY_PASTE') intScore -= 10;
      else intScore -= 5;
    });
  }
  intScore = Math.max(0, intScore);
  const intColor = intScore < 70 ? colors.error : (intScore < 90 ? colors.warning : colors.success);
  drawStatCard('Integrity Score', `${intScore}%`, intScore < 70 ? colors.errorBg : (intScore < 90 ? colors.warningBg : colors.successBg), intColor);

  currentY += 80;

  // ─── Executive Summary ───
  if (result.aiSummary) {
    doc.roundedRect(margin, currentY, contentWidth, 20, 4).fill(colors.bg); // Placeholder for height, will recalculate
    doc.fontSize(11).font('Helvetica-Bold').fillColor(colors.primary).text('Executive Summary', margin + 15, currentY + 15);
    
    doc.font('Helvetica').fontSize(10).fillColor(colors.text);
    const sumHeight = doc.heightOfString(result.aiSummary, { width: contentWidth - 30, align: 'justify', lineGap: 3 });
    
    // Redraw rect with proper height
    doc.roundedRect(margin, currentY, contentWidth, sumHeight + 45, 6).fill(colors.bg).strokeColor(colors.border).lineWidth(1).stroke();
    doc.fontSize(12).font('Helvetica-Bold').fillColor(colors.primary).text('Executive Summary', margin + 15, currentY + 15);
    doc.font('Helvetica').fontSize(10).fillColor(colors.text).text(result.aiSummary, margin + 15, currentY + 35, { width: contentWidth - 30, align: 'justify', lineGap: 3 });
    
    currentY += sumHeight + 65;
  }

  // ─── Performance Breakdown (Progress Bars) ───
  currentY = addSectionTitle('Performance Breakdown', currentY, 20);

  const accScore = totalQuestions > 0 ? (correctAnswers / totalQuestions) * 100 : 0;
  
  const bars = [
    { label: 'Technical Skills', val: result.technicalScore },
    { label: 'Communication', val: result.communicationScore },
    { label: 'Problem Solving', val: result.problemSolvingScore },
    { label: 'Domain Knowledge', val: result.domainKnowledgeScore },
    { label: 'Confidence', val: result.confidenceScore },
    { label: 'Accuracy', val: accScore }
  ].filter(b => b.val != null);

  const barW = (contentWidth - 40) / 2;
  
  bars.forEach((b, idx) => {
    if (currentY > doc.page.height - 60) { doc.addPage(); currentY = 50; }
    
    const isRight = idx % 2 === 1;
    const bX = margin + (isRight ? barW + 40 : 0);
    const bY = isRight ? currentY - 30 : currentY;
    
    doc.fontSize(10).font('Helvetica-Bold').fillColor(colors.secondary).text(b.label, bX, bY);
    doc.fontSize(10).font('Helvetica').fillColor(colors.light).text(`${Math.round(b.val!)}%`, bX, bY, { width: barW, align: 'right' });
    
    // Progress Bar Background
    doc.roundedRect(bX, bY + 15, barW, 8, 4).fill(colors.border);
    // Progress Bar Fill
    const fillW = Math.max(8, (Math.min(100, b.val!) / 100) * barW);
    const barColor = b.val! < 50 ? colors.error : (b.val! < 75 ? colors.warning : colors.success);
    doc.roundedRect(bX, bY + 15, fillW, 8, 4).fill(barColor);
    
    if (isRight) currentY += 25;
    else if (idx === bars.length - 1) currentY += 30; // last item odd
  });

  currentY += 20;

  // ─── Question Analysis (Table) ───
  if (interview.answers && interview.answers.length > 0) {
    currentY = addSectionTitle('Question Analysis', currentY, 20);

    const colQ = 140;
    const colA = 180;
    const colE = 120;
    const colR = 50;
    
    // Header
    doc.roundedRect(margin, currentY, contentWidth, 25, 4).fill(colors.bg);
    let hY = currentY + 7;
    doc.fontSize(9).font('Helvetica-Bold').fillColor(colors.secondary);
    doc.text('Question', margin + 10, hY, { width: colQ - 10 });
    doc.text('Candidate Answer', margin + colQ + 10, hY, { width: colA - 10 });
    doc.text('Evaluation', margin + colQ + colA + 10, hY, { width: colE - 10 });
    doc.text('Result', margin + colQ + colA + colE + 10, hY, { width: colR - 10, align: 'center' });
    
    currentY += 30;

    interview.answers.forEach((ans) => {
      const qText = ans.question?.text || 'Unknown';
      const aText = ans.answerText || ans.answerCode || '-';
      const evalText = ans.aiReasoning || ans.aiEvaluation || '-';
      
      doc.fontSize(9).font('Helvetica');
      const h1 = doc.heightOfString(qText, { width: colQ - 15, lineGap: 2 });
      const h2 = doc.heightOfString(aText, { width: colA - 15, lineGap: 2 });
      const h3 = doc.heightOfString(evalText, { width: colE - 15, lineGap: 2 });
      const rowH = Math.max(h1, h2, h3, 20) + 15;

      if (currentY + rowH > doc.page.height - 60) {
        doc.addPage();
        currentY = 50;
      }

      // Border bottom
      doc.moveTo(margin, currentY + rowH).lineTo(margin + contentWidth, currentY + rowH).strokeColor(colors.border).lineWidth(0.5).stroke();

      let rY = currentY + 7;
      doc.fillColor(colors.text);
      doc.text(qText, margin + 10, rY, { width: colQ - 15, lineGap: 2 });
      doc.text(aText, margin + colQ + 10, rY, { width: colA - 15, lineGap: 2 });
      doc.text(evalText, margin + colQ + colA + 10, rY, { width: colE - 15, lineGap: 2 });
      
      const isCorrect = ans.isCorrect;
      const resText = isCorrect === true ? 'Correct' : (isCorrect === false ? 'Wrong' : 'Partial');
      const resCol = isCorrect === true ? colors.success : (isCorrect === false ? colors.error : colors.warning);
      doc.font('Helvetica-Bold').fillColor(resCol).text(resText, margin + colQ + colA + colE + 10, rY, { width: colR - 10, align: 'center' });

      currentY += rowH;
    });

    currentY += 20;
  }

  // ─── Media Section ───
  if (interview.recordingUrl || interview.transcriptUrl) {
    currentY = addSectionTitle('Media & Attachments', currentY, 20);
    
    let mX = margin;
    const drawMediaLink = (label: string, url: string) => {
       doc.roundedRect(mX, currentY, 200, 40, 6).fill(colors.bg).strokeColor(colors.border).lineWidth(1).stroke();
       doc.fontSize(10).font('Helvetica-Bold').fillColor('#2563eb').text(label, mX + 15, currentY + 15, { link: url, underline: true });
       mX += 220;
    };
    
    if (interview.recordingUrl) drawMediaLink('▶ View Recording', interview.recordingUrl);
    if (interview.transcriptUrl) drawMediaLink('📄 View Transcript', interview.transcriptUrl);
    
    currentY += 60;
  }

  // ─── Proctoring Dashboard ───
  if (interview.violations && Array.isArray(interview.violations)) {
    const logs = interview.violations as any[];
    
    currentY = addSectionTitle('Proctoring Dashboard', currentY, 20);
    
    let multiPerson = 0, faceMissing = 0, mobile = 0, tabSwitch = 0, noise = 0;
    logs.forEach(v => {
      if (v.type === 'MULTIPLE_FACES') multiPerson++;
      else if (v.type === 'MOBILE_PHONE') mobile++;
      else if (v.type === 'NO_FACE') faceMissing++;
      else if (v.type === 'TAB_SWITCH' || v.type === 'WINDOW_BLUR' || v.type === 'FULLSCREEN_EXIT') tabSwitch++;
      else if (v.type === 'MULTIPLE_VOICES' || v.type === 'UNUSUAL_NOISE') noise++;
    });

    let riskLevel = 'Low Risk';
    if (intScore < 70) riskLevel = 'High Risk';
    else if (intScore < 90) riskLevel = 'Medium Risk';
    const riskColor = riskLevel === 'High Risk' ? colors.error : riskLevel === 'Medium Risk' ? colors.warning : colors.success;

    // Header for Proctoring Dashboard Table
    doc.roundedRect(margin, currentY, contentWidth, 25, 4).fill(colors.bg);
    doc.fontSize(9).font('Helvetica-Bold').fillColor(colors.secondary);
    doc.text('Metric', margin + 10, currentY + 7, { width: 200 });
    doc.text('Value', margin + 220, currentY + 7, { width: 100 });
    doc.text('Status', margin + 330, currentY + 7, { width: 100 });
    currentY += 30;

    const addDashboardRow = (label: string, valText: string, valColor: string, statText: string, statColor: string) => {
      if (currentY > doc.page.height - 50) { doc.addPage(); currentY = 50; }
      
      doc.moveTo(margin, currentY + 25).lineTo(margin + contentWidth, currentY + 25).strokeColor(colors.border).lineWidth(0.5).stroke();
      
      doc.fontSize(9).font('Helvetica').fillColor(colors.text).text(label, margin + 10, currentY + 7, { width: 200 });
      doc.font('Helvetica-Bold').fillColor(valColor).text(valText, margin + 220, currentY + 7, { width: 100 });
      doc.fillColor(statColor).text(statText, margin + 330, currentY + 7, { width: 100 });
      
      currentY += 25;
    };

    // Draw rows
    addDashboardRow('Final Integrity Risk', riskLevel, riskColor, intScore >= 90 ? 'Pass' : 'Review', riskColor);
    
    const drawCountRow = (label: string, count: number, isHighSeverity: boolean) => {
      const isOk = count === 0;
      const statusText = isOk ? 'OK' : 'Warning';
      const color = isOk ? colors.success : (isHighSeverity ? colors.error : colors.warning);
      addDashboardRow(label, String(count), color, statusText, color);
    };

    drawCountRow('Multiple Faces Detected', multiPerson, true);
    drawCountRow('Tab / Window Switches', tabSwitch, false);
    drawCountRow('Face Missing Events', faceMissing, false);
    drawCountRow('Mobile Phone Detected', mobile, true);
    drawCountRow('Unusual Noise / Voices', noise, false);
    
    currentY += 10;
    
    // Violations Table
    if (logs.length > 0) {
       if (currentY > doc.page.height - 100) { doc.addPage(); currentY = 50; }
       
       doc.fontSize(12).font('Helvetica-Bold').fillColor(colors.secondary).text(`Violation Log (${logs.length})`, margin, currentY);
       currentY += 20;
       
       // Header
       doc.roundedRect(margin, currentY, contentWidth, 25, 4).fill(colors.bg);
       doc.fontSize(9).font('Helvetica-Bold').fillColor(colors.secondary);
       doc.text('Time', margin + 10, currentY + 7, { width: 80 });
       doc.text('Violation Type', margin + 90, currentY + 7, { width: 140 });
       doc.text('Severity', margin + 230, currentY + 7, { width: 70 });
       doc.text('Description', margin + 300, currentY + 7, { width: 190 });
       
       currentY += 30;
       
       logs.forEach(v => {
         const tStr = v.at ? new Date(v.at).toLocaleTimeString('en-GB', { timeZone: timezone }) : '-';
         const typeStr = (v.type || 'Unknown').replace(/_/g, ' ');
         const sev = ['MULTIPLE_FACES', 'MOBILE_PHONE', 'COPY_PASTE'].includes(v.type) ? 'High' : 'Medium';
         const sevCol = sev === 'High' ? colors.error : colors.warning;
         const desc = v.detail || '-';
         
         doc.fontSize(9).font('Helvetica');
         const rh = Math.max(
           doc.heightOfString(typeStr, { width: 140 }),
           doc.heightOfString(desc, { width: 190 })
         ) + 15;
         
         if (currentY + rh > doc.page.height - 50) { doc.addPage(); currentY = 50; }
         
         doc.moveTo(margin, currentY + rh).lineTo(margin + contentWidth, currentY + rh).strokeColor(colors.border).lineWidth(0.5).stroke();
         
         doc.fillColor(colors.text).text(tStr, margin + 10, currentY + 7, { width: 80 });
         doc.text(typeStr, margin + 90, currentY + 7, { width: 140 });
         doc.font('Helvetica-Bold').fillColor(sevCol).text(sev, margin + 230, currentY + 7, { width: 70 });
         doc.font('Helvetica').fillColor(colors.light).text(desc, margin + 300, currentY + 7, { width: 190 });
         
         currentY += rh;
       });
       
       currentY += 20;
    }
  }

  // ─── Evidence Screenshots ───
  if (interview.proctorShots && interview.proctorShots.length > 0) {
    currentY = addSectionTitle('Evidence Screenshots', currentY, 20);
    
    const cols = 2; // 2 images per row for bigger images
    const padding = 20;
    const thumbWidth = (contentWidth - padding) / 2;
    const thumbHeight = (thumbWidth / 16) * 9;
    
    let col = 0;
    
    interview.proctorShots.forEach((shot) => {
      // Need 40px for captions
      if (col === 0 && currentY > doc.page.height - thumbHeight - 70) {
        doc.addPage();
        currentY = 50;
      }
      
      const x = margin + col * (thumbWidth + padding);
      const y = currentY;
      
      // Draw rounded container for image
      doc.roundedRect(x, y, thumbWidth, thumbHeight, 8).fill('#f1f5f9').strokeColor(colors.border).lineWidth(1).stroke();
      
      try {
        if (shot.imageData) {
          // Native rounded image clipping is not easily supported. Drawing image slightly inset or as is.
          doc.image(shot.imageData, x, y, { width: thumbWidth, height: thumbHeight });
          // Overlay rounded border to "clip" corners visually
          doc.roundedRect(x, y, thumbWidth, thumbHeight, 8).strokeColor(colors.border).lineWidth(2).stroke();
        } else {
          doc.fontSize(10).fillColor(colors.light).text('Image missing', x, y + thumbHeight/2 - 5, { width: thumbWidth, align: 'center' });
        }
      } catch (err) {
        doc.fontSize(10).fillColor(colors.light).text('Failed to load', x, y + thumbHeight/2 - 5, { width: thumbWidth, align: 'center' });
      }
      
      const reasonLabel = shot.reason === 'START' ? 'Start' : shot.reason === 'PERIODIC' ? 'Routine' : shot.reason === 'VIOLATION' ? 'On violation' : 'At termination';
      const timeStr = shot.capturedAt ? shot.capturedAt.toLocaleString('en-GB', { timeZone: timezone, hour: '2-digit', minute: '2-digit', second: '2-digit' }) : 'Unknown';
      
      doc.fontSize(9).font('Helvetica-Bold').fillColor(colors.secondary).text(reasonLabel, x, y + thumbHeight + 10);
      doc.fontSize(8).font('Helvetica').fillColor(colors.light).text(timeStr, x, y + thumbHeight + 22);
      
      col++;
      if (col >= cols) {
        col = 0;
        currentY += thumbHeight + 50;
      }
    });
    
    currentY += (col > 0 ? thumbHeight + 50 : 0);
  }
}

export async function generateInterviewReportPDF(interviewId: string, ctx?: any): Promise<Buffer> {
  const interview = await prisma.interview.findUnique({
    where: { id: interviewId },
    include: INTERVIEW_REPORT_INCLUDE,
  });

  if (!interview || !interview.result) {
    throw new NotFoundError('Interview or results not found');
  }

  let generatedBy = 'Recruiter';
  if (ctx?.userId) {
    const user = await prisma.user.findUnique({
      where: { id: ctx.userId },
      select: { fullName: true }
    });
    if (user?.fullName) generatedBy = user.fullName;
  }

  const timezone = await resolveTenantTimezone((interview as { tenantId?: string | null }).tenantId);

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, bufferPages: true, size: 'A4' });
      const buffers: Buffer[] = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      renderInterviewReport(doc, interview as any, timezone, generatedBy);
      
      // ─── Footer ───
      const pageWidth = doc.page.width;
      const margin = 50;
      const contentWidth = pageWidth - margin * 2;
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        doc.rect(0, doc.page.height - 40, pageWidth, 40).fill('#f8fafc');
        doc.moveTo(0, doc.page.height - 40).lineTo(pageWidth, doc.page.height - 40).strokeColor('#e2e8f0').lineWidth(1).stroke();
        const footerText = `Page ${i + 1} of ${range.count}  |  Generated securely by AgnoHire`;
        const fWidth = doc.fontSize(9).font('Helvetica').widthOfString(footerText);
        const fX = margin + (contentWidth - fWidth) / 2;
        doc.fillColor('#64748b').text(
          footerText,
          fX,
          doc.page.height - 25,
          { lineBreak: false }
        );
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

export async function generateBulkInterviewReportsPDF(
  interviewIds: string[],
  ctx?: any
): Promise<{ buffer: Buffer; filename: string }> {
  const interviews = await prisma.interview.findMany({
    where: { id: { in: interviewIds }, result: { isNot: null } },
    include: INTERVIEW_REPORT_INCLUDE,
  });

  if (interviews.length === 0) {
    throw new NotFoundError('No evaluated interviews found to export');
  }

  let generatedBy = 'Recruiter';
  if (ctx?.userId) {
    const user = await prisma.user.findUnique({
      where: { id: ctx.userId },
      select: { fullName: true }
    });
    if (user?.fullName) generatedBy = user.fullName;
  }

  const timezone = await resolveTenantTimezone((interviews[0] as { tenantId?: string | null }).tenantId);
  const filename = `Interview_Reports_${new Date().toLocaleDateString('en-GB', { timeZone: timezone }).replace(/\//g, '-')}.pdf`;

  const buffer = await new Promise<Buffer>((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, bufferPages: true, size: 'A4' });
      const buffers: Buffer[] = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      interviews.forEach((interview, idx) => {
        if (idx > 0) doc.addPage();
        renderInterviewReport(doc, interview as any, timezone, generatedBy);
      });
      
      const pageWidth = doc.page.width;
      const margin = 50;
      const contentWidth = pageWidth - margin * 2;
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        doc.rect(0, doc.page.height - 40, pageWidth, 40).fill('#f8fafc');
        doc.moveTo(0, doc.page.height - 40).lineTo(pageWidth, doc.page.height - 40).strokeColor('#e2e8f0').lineWidth(1).stroke();
        const footerText = `Page ${i + 1} of ${range.count}  |  Generated securely by AgnoHire`;
        const fWidth = doc.fontSize(9).font('Helvetica').widthOfString(footerText);
        const fX = margin + (contentWidth - fWidth) / 2;
        doc.fillColor('#64748b').text(
          footerText,
          fX,
          doc.page.height - 25,
          { lineBreak: false }
        );
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });

  return { buffer, filename };
}

export async function generateQuestionBankPDF(
  bankIds: string[],
  ctx: any
): Promise<{ buffer: Buffer; filename: string }> {
  const user = await prisma.user.findUnique({
    where: { id: ctx.userId },
    select: { fullName: true }
  });
  const generatedBy = user?.fullName ?? 'Recruiter';

  const banks = await prisma.questionBank.findMany({
    where: { id: { in: bankIds }, tenantId: ctx.tenantId },
    include: { questions: true }
  });

  if (banks.length === 0) {
    throw new NotFoundError('No question banks found to export');
  }

  const timezone = await resolveTenantTimezone(ctx.tenantId);
  const filename = `Question_Banks_${new Date().toLocaleDateString('en-GB', { timeZone: timezone }).replace(/\//g, '-')}.pdf`;

  const buffer = await new Promise<Buffer>((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, bufferPages: true, size: 'A4' });
      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      banks.forEach((bank, idx) => {
        if (idx > 0) doc.addPage();
        
        const pageWidth = doc.page.width;
        const margin = 50;
        
        doc.rect(0, 0, pageWidth, 120).fill('#0f172a');
        doc.fontSize(32).font('Helvetica-Bold').fillColor('#ffffff').text('AgnoHire', margin, 40);
        doc.fontSize(14).font('Helvetica').fillColor('#94a3b8').text('Question Bank', margin, 75);
        doc.fontSize(10).font('Helvetica').fillColor('#94a3b8').text(`Generated by: ${generatedBy}`, margin, 95);

        // Right Aligned Header Text
        const rightTextX = pageWidth - margin - 200;
        const generatedStr = new Date().toLocaleString('en-GB', { timeZone: timezone });
        doc.fontSize(10).font('Helvetica').fillColor('#94a3b8').text('Confidential', rightTextX, 45, { width: 200, align: 'right' });
        doc.fontSize(9).text(`Date: ${generatedStr}`, rightTextX, 60, { width: 200, align: 'right' });
        doc.fontSize(9).text(`ID: ${bank.id.substring(0, 8).toUpperCase()}`, rightTextX, 73, { width: 200, align: 'right' });

        let currentY = 150;
        doc.fontSize(18).font('Helvetica-Bold').fillColor('#0f172a').text(bank.name, margin, currentY);
        currentY += 30;

        bank.questions.forEach((q, qIndex) => {
          if (doc.y > doc.page.height - 100) { doc.addPage(); currentY = 50; }
          
          doc.fontSize(12).font('Helvetica-Bold').fillColor('#1e293b').text(`Q${qIndex + 1}: ${q.text}`, margin, currentY);
          currentY = doc.y + 15;
          
          if (q.type === 'MCQ' && Array.isArray(q.options)) {
            q.options.forEach((opt: any) => {
              const prefix = opt.correct ? '✓ ' : '· ';
              const color = opt.correct ? '#16a34a' : '#64748b';
              doc.fontSize(11).font(opt.correct ? 'Helvetica-Bold' : 'Helvetica').fillColor(color).text(`${prefix}${opt.text}`, margin + 15, currentY);
              currentY = doc.y + 5;
            });
          }
          currentY += 15;
        });
      });

      // ─── Footer ───
      const pageWidth = doc.page.width;
      const margin = 50;
      const contentWidth = pageWidth - margin * 2;
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        doc.rect(0, doc.page.height - 40, pageWidth, 40).fill('#f8fafc');
        doc.moveTo(0, doc.page.height - 40).lineTo(pageWidth, doc.page.height - 40).strokeColor('#e2e8f0').lineWidth(1).stroke();
        
        const footerText = `Page ${i + 1} of ${range.count}  |  Generated securely by AgnoHire`;
        const fWidth = doc.fontSize(9).font('Helvetica').widthOfString(footerText);
        const fX = margin + (contentWidth - fWidth) / 2;
        doc.fillColor('#64748b').text(
          footerText,
          fX,
          doc.page.height - 25,
          { lineBreak: false }
        );
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });

  return { buffer, filename };
}

export async function generateJobRequisitionPDF(
  jobId: string,
  timezone: string,
  ctx?: any
): Promise<{ buffer: Buffer; filename: string }> {
  const job = await prisma.jobRequisition.findUnique({
    where: { id: jobId },
    include: {
      sector: true,
      domain: true,
      workflowRounds: {
        orderBy: { sequenceOrder: 'asc' }
      }
    }
  });

  if (!job) {
    throw new NotFoundError('Job not found');
  }

  let generatedBy = 'Recruiter';
  if (ctx?.userId) {
    const user = await prisma.user.findUnique({
      where: { id: ctx.userId },
      select: { fullName: true }
    });
    if (user?.fullName) generatedBy = user.fullName;
  }

  const filename = `Job_${job.title.replace(/\s+/g, '_')}.pdf`;

  const buffer = await new Promise<Buffer>((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, bufferPages: true, size: 'A4' });
      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      const pageWidth = doc.page.width;
      const margin = 50;
      const contentWidth = pageWidth - margin * 2;
      
      // ─── Header ───
      doc.rect(0, 0, pageWidth, 120).fill('#0f172a');
      doc.fontSize(32).font('Helvetica-Bold').fillColor('#ffffff').text('AgnoHire', margin, 40);
      doc.fontSize(14).font('Helvetica').fillColor('#94a3b8').text('Job Requisition Details', margin, 75);
      doc.fontSize(10).font('Helvetica').fillColor('#94a3b8').text(`Generated by: ${generatedBy}`, margin, 95);

      // Right Aligned Header Text
      const rightTextX = pageWidth - margin - 200;
      const generatedStr = new Date().toLocaleString('en-GB', { timeZone: timezone });
      doc.fontSize(10).font('Helvetica').fillColor('#94a3b8').text('Confidential', rightTextX, 45, { width: 200, align: 'right' });
      doc.fontSize(9).text(`Date: ${generatedStr}`, rightTextX, 60, { width: 200, align: 'right' });
      doc.fontSize(9).text(`ID: ${job.id.substring(0, 8).toUpperCase()}`, rightTextX, 73, { width: 200, align: 'right' });

      let currentY = 150;
      
      // ─── Title ───
      doc.fontSize(24).font('Helvetica-Bold').fillColor('#0f172a').text(job.title, margin, currentY);
      currentY += 35;
      
      // ─── Badges ───
      const badges = [
        { text: job.status.toUpperCase(), bg: '#dbeafe', color: '#2563eb' },
        job.workMode ? { text: job.workMode.toUpperCase(), bg: '#dcfce7', color: '#16a34a' } : null,
        job.sector ? { text: job.sector.name, bg: '#f3e8ff', color: '#9333ea' } : null,
        job.domain ? { text: job.domain.name, bg: '#fef08a', color: '#ca8a04' } : null
      ].filter(Boolean) as {text: string, bg: string, color: string}[];

      let badgeX = margin;
      badges.forEach(b => {
        doc.fontSize(10).font('Helvetica-Bold');
        const textWidth = doc.widthOfString(b.text);
        const w = textWidth + 16;
        const h = 20;
        // Check for page break (unlikely here, but good practice)
        if (badgeX + w > pageWidth - margin) {
           badgeX = margin;
           currentY += 25;
        }
        
        doc.rect(badgeX, currentY, w, h).fill(b.bg);
        doc.fillColor(b.color).text(b.text, badgeX + 8, currentY + 5.5, { lineBreak: false });
        badgeX += w + 10;
      });
      
      currentY += 40;

      // ─── Helper for Sections ───
      const addSection = (title: string, yPos: number, drawLine: boolean = true) => {
        if (yPos > doc.page.height - 100) { doc.addPage(); yPos = 50; }
        doc.fontSize(14).font('Helvetica-Bold').fillColor('#1e293b').text(title, margin, yPos);
        if (drawLine) {
          doc.moveTo(margin, yPos + 18).lineTo(pageWidth - margin, yPos + 18).strokeColor('#cbd5e1').lineWidth(1).stroke();
        }
        return yPos + 30;
      };

      // ─── Job Details ───
      currentY = addSection('Job Details', currentY);
      
      const formatCurrency = (val: any) => val ? `${val}` : '';
      const budgetStr = (job.budgetMin || job.budgetMax) 
        ? `${formatCurrency(job.budgetMin)} - ${formatCurrency(job.budgetMax)}`
        : 'Not specified';
      
      const expStr = (job.experienceMin != null || job.experienceMax != null)
        ? `${job.experienceMin ?? 0} - ${job.experienceMax ?? 'Any'} years`
        : 'Not specified';

      const details = [
        { label: 'Location:', val: job.location || 'Remote' },
        { label: 'Headcount:', val: job.headcount.toString() },
        { label: 'Budget/Salary:', val: budgetStr },
        { label: 'Deadline:', val: job.deadline ? job.deadline.toLocaleDateString('en-GB') : 'No deadline' },
        { label: 'Experience:', val: expStr },
        { label: 'Rounds:', val: job.workflowRounds.length.toString() }
      ];

      details.forEach((d, i) => {
        const x = margin + (i % 2) * (contentWidth / 2);
        const y = currentY + Math.floor(i / 2) * 25;
        doc.fontSize(10).font('Helvetica-Bold').fillColor('#475569').text(d.label, x, y);
        doc.font('Helvetica').fillColor('#1e293b').text(d.val, x + 90, y);
      });
      
      currentY += Math.ceil(details.length / 2) * 25 + 15;

      // ─── Required Skills ───
      if (job.skills && job.skills.length > 0) {
        currentY = addSection('Required Skills', currentY);
        doc.y = currentY;
        job.skills.forEach(skill => {
          if (doc.y > doc.page.height - 60) { doc.addPage(); doc.y = 50; }
          doc.fontSize(10).font('Helvetica').fillColor('#475569').text(`• ${skill}`, margin + 5, doc.y);
          doc.y += 4;
        });
        currentY = doc.y + 15;
      }

      // ─── Interview Workflow ───
      if (job.workflowRounds && job.workflowRounds.length > 0) {
        currentY = addSection('Interview Workflow', currentY);
        doc.y = currentY;
        job.workflowRounds.forEach((round, i) => {
          if (doc.y > doc.page.height - 60) { doc.addPage(); doc.y = 50; }
          doc.fontSize(10).font('Helvetica').fillColor('#475569').text(`• Round ${i + 1}: ${round.roundName} (${round.roundType})`, margin + 5, doc.y);
          doc.y += 4;
        });
        currentY = doc.y + 15;
      }

      // ─── Job Description ───
      if (job.description) {
        currentY = addSection('Job Description', currentY, false);
        doc.y = currentY;
        
        // Strip basic HTML if there is any (optional, assume it's plain text or very basic HTML)
        const strippedDesc = job.description.replace(/<[^>]*>?/gm, ''); 
        
        doc.fontSize(10).font('Helvetica').fillColor('#475569').text(strippedDesc, margin, doc.y, { align: 'justify', width: contentWidth });
      }

      // ─── Footer ───
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        doc.rect(0, doc.page.height - 40, pageWidth, 40).fill('#f8fafc');
        doc.moveTo(0, doc.page.height - 40).lineTo(pageWidth, doc.page.height - 40).strokeColor('#e2e8f0').lineWidth(1).stroke();
        
        const footerText = `Page ${i + 1} of ${range.count}  |  Generated securely by AgnoHire`;
        const fWidth = doc.fontSize(9).font('Helvetica').widthOfString(footerText);
        const fX = margin + (contentWidth - fWidth) / 2;
        doc.fillColor('#64748b').text(
          footerText,
          fX,
          doc.page.height - 25,
          { lineBreak: false }
        );
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });

  return { buffer, filename };
}

export async function generateCandidatesPDF(filters: any, ctx: any): Promise<{ buffer: Buffer, filename: string }> {
  const candidateService = await import('./candidateService.js');
  const PDFDocument = (await import('pdfkit')).default || await import('pdfkit'); // Handle CJS/ESM
  
  const exportFilters = { ...filters, page: 1, limit: 10000 };
  const result = await candidateService.listCandidates(exportFilters, ctx);
  
  let generatedBy = 'Recruiter';
  if (ctx?.userId) {
    const user = await prisma.user.findUnique({
      where: { id: ctx.userId },
      select: { fullName: true }
    });
    if (user?.fullName) generatedBy = user.fullName;
  }
  const timezone = await resolveTenantTimezone(ctx?.tenantId);

  // Need to instantiate PDFDocument safely depending on how the module is resolved
  const DocConstructor = typeof PDFDocument === 'function' ? PDFDocument : (PDFDocument as any).default || PDFDocument;
  const doc = new DocConstructor({ margin: 50, bufferPages: true, size: 'A4' });
  
  const buffer = await new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    
    const margin = 50;
    const pageWidth = doc.page.width;
    const contentWidth = pageWidth - margin * 2;
    
    // ─── Header ───
    doc.rect(0, 0, pageWidth, 120).fill('#0f172a');
    doc.fontSize(32).font('Helvetica-Bold').fillColor('#ffffff').text('AgnoHire', margin, 40);
    doc.fontSize(14).font('Helvetica').fillColor('#94a3b8').text('Candidates Report', margin, 75);
    doc.fontSize(10).font('Helvetica').fillColor('#94a3b8').text(`Generated by: ${generatedBy}`, margin, 95);

    // Right Aligned Header Text
    const rightTextX = pageWidth - margin - 200;
    const generatedStr = new Date().toLocaleString('en-GB', { timeZone: timezone });
    doc.fontSize(10).font('Helvetica').fillColor('#94a3b8').text('Confidential', rightTextX, 45, { width: 200, align: 'right' });
    doc.fontSize(9).text(`Date: ${generatedStr}`, rightTextX, 60, { width: 200, align: 'right' });
    doc.fontSize(9).text(`ID: EXPORT`, rightTextX, 73, { width: 200, align: 'right' });

    let currentY = 150;
    doc.y = currentY;
    doc.x = margin;
    result.items.forEach((c: any, i: number) => {
      if (doc.y > doc.page.height - 100) { doc.addPage(); }
      doc.fontSize(12).font('Helvetica-Bold').fillColor('#334155').text(`${i + 1}. ${c.fullName || 'N/A'}`, margin);
      doc.fontSize(10).font('Helvetica').fillColor('#64748b').text(`Email: ${c.email || 'N/A'} | Phone: ${c.phone || 'N/A'}`, margin);
      doc.text(`Source: ${c.source || 'N/A'} | Experience: ${c.experienceLevel || 'N/A'} | Role: ${c.currentRole || 'N/A'}`, margin);
      doc.text(`Fit Score: ${c.fitScore !== null ? c.fitScore + '%' : 'N/A'}`, margin);
      doc.moveDown(1);
    });
    
    // ─── Footer ───
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc.rect(0, doc.page.height - 40, pageWidth, 40).fill('#f8fafc');
      doc.moveTo(0, doc.page.height - 40).lineTo(pageWidth, doc.page.height - 40).strokeColor('#e2e8f0').lineWidth(1).stroke();
      
      const footerText = `Page ${i + 1} of ${range.count}  |  Generated securely by AgnoHire`;
      const fWidth = doc.fontSize(9).font('Helvetica').widthOfString(footerText);
      const fX = margin + (contentWidth - fWidth) / 2;
      doc.fillColor('#64748b').text(
        footerText,
        fX,
        doc.page.height - 25,
        { lineBreak: false }
      );
    }

    doc.end();
  });
  
  return {
    buffer,
    filename: `Candidates_Export_${new Date().toISOString().split('T')[0]}.pdf`
  };
}

/** Cohesive chart palette — matches CHART_COLORS in
 * client/src/components/dashboard/DashboardCharts.tsx so PDF breakdowns use
 * the same colors as the on-screen donut/bar charts. */
const SNAPSHOT_CHART_COLORS = ['#6366f1', '#0ea5e9', '#059669', '#d97706', '#e11d48', '#818cf8', '#a5b4fc'];

/** Renders an Analytics snapshot onto the given (already-open) PDF document,
 * matching the same header/footer/color template used by the interview report
 * above, and mirroring the exact layout of the in-app Snapshot drawer: the KPI
 * card grid followed by the four breakdown sections (jobs/applications by
 * status, candidates by source, interviews by status). */
function renderAnalyticsSnapshotReport(
  doc: PDFKit.PDFDocument,
  period: string,
  snapshotAt: Date,
  dashboard: AnalyticsDashboard,
  generatedBy: string,
  timezone: string,
): void {
  const pageWidth = doc.page.width;
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;

  const colors = {
    primary: '#0f172a',
    secondary: '#1e293b',
    text: '#475569',
    light: '#64748b',
    muted: '#94a3b8',
    border: '#e2e8f0',
    bg: '#f8fafc',
    white: '#ffffff',
    accent: '#3b6df8',
    accentMuted: '#eff4ff',
    emerald: '#059669',
    emeraldMuted: '#ecfdf5',
    blue: '#2563eb',
    blueMuted: '#eff6ff',
  };

  // ─── Header ───
  doc.rect(0, 0, pageWidth, 120).fill(colors.primary);
  doc.fontSize(32).font('Helvetica-Bold').fillColor(colors.white).text('AgnoHire', margin, 40);
  doc.fontSize(14).font('Helvetica').fillColor(colors.muted).text('Analytics Snapshot Report', margin, 75);
  doc.fontSize(10).font('Helvetica').fillColor(colors.muted).text(`Generated by: ${generatedBy}`, margin, 95);

  const rightTextX = pageWidth - margin - 200;
  const generatedStr = new Date().toLocaleString('en-GB', { timeZone: timezone });
  const capturedStr = snapshotAt.toLocaleString('en-GB', { timeZone: timezone });
  doc.fontSize(10).font('Helvetica').fillColor(colors.muted).text('Confidential', rightTextX, 40, { width: 200, align: 'right' });
  doc.fontSize(9).text(`Captured: ${capturedStr}`, rightTextX, 58, { width: 200, align: 'right' });
  doc.fontSize(9).text(`Exported: ${generatedStr}`, rightTextX, 71, { width: 200, align: 'right' });
  doc.fontSize(9).text(`Range: ${dashboard.range.from} - ${dashboard.range.to}`, rightTextX, 84, { width: 200, align: 'right' });

  let currentY = 145;
  doc.fontSize(9).font('Helvetica').fillColor(colors.light).text(`Period: ${period}`, margin, currentY);
  currentY += 22;

  const addSectionTitle = (title: string, yPos: number, spacing = 18) => {
    if (yPos > doc.page.height - 120) { doc.addPage(); yPos = 40; }
    doc.fontSize(14).font('Helvetica-Bold').fillColor(colors.primary).text(title, margin, yPos);
    return yPos + spacing;
  };

  // ─── KPI card grid (mirrors the Snapshot drawer's KpiGrid: 4 cols x 2 rows) ───
  const kpis = dashboard.kpis;
  const cards: { label: string; value: string; sub: string; trend: string; trendUp: boolean }[] = [
    { label: 'OPEN JOBS', value: String(kpis.openJobs), sub: `${kpis.totalJobs} total`, trend: '+4%', trendUp: true },
    { label: 'CANDIDATES', value: String(kpis.totalCandidates), sub: 'in range', trend: '+12%', trendUp: true },
    { label: 'APPLICATIONS', value: String(kpis.totalApplications), sub: 'in range', trend: '+8%', trendUp: true },
    { label: 'INTERVIEWS', value: String(kpis.interviewsTotal), sub: `${kpis.interviewsCompleted} completed`, trend: '+15%', trendUp: true },
    {
      label: 'SCHEDULE',
      value: String(kpis.assessmentsAssigned),
      sub: `${kpis.assessmentsPassed} passed`,
      trend: kpis.assessmentsAssigned > 0 ? `${Math.round((kpis.assessmentsPassed / kpis.assessmentsAssigned) * 100)}% pass` : '0% pass',
      trendUp: true,
    },
    { label: 'HIRES', value: String(kpis.hires), sub: `${kpis.offersExtended} offers`, trend: '+2 new', trendUp: true },
    { label: 'OFFER ACCEPTANCE', value: kpis.offerAcceptanceRate != null ? `${kpis.offerAcceptanceRate}%` : '—', sub: 'accepted / extended', trend: 'Strong', trendUp: true },
    { label: 'TIME TO HIRE', value: kpis.avgTimeToHireDays != null ? `${kpis.avgTimeToHireDays}d` : '—', sub: 'avg, applied to hired', trend: '-3 days', trendUp: false },
  ];

  const cardGap = 10;
  const cardCols = 4;
  const cardWidth = (contentWidth - cardGap * (cardCols - 1)) / cardCols;
  const cardHeight = 78;
  cards.forEach((c, i) => {
    const col = i % cardCols;
    const row = Math.floor(i / cardCols);
    const x = margin + col * (cardWidth + cardGap);
    const y = currentY + row * (cardHeight + cardGap);
    doc.roundedRect(x, y, cardWidth, cardHeight, 10).fillAndStroke(colors.white, colors.border);
    doc.fontSize(8).font('Helvetica-Bold').fillColor(colors.light).text(c.label, x + 12, y + 12, { width: cardWidth - 24 });
    doc.fontSize(20).font('Helvetica-Bold').fillColor(colors.primary).text(c.value, x + 12, y + 26, { width: cardWidth - 24 });
    doc.fontSize(8).font('Helvetica').fillColor(colors.light).text(c.sub, x + 12, y + cardHeight - 20, { width: cardWidth - 70 });
    const trendBg = c.trendUp ? colors.emeraldMuted : colors.blueMuted;
    const trendColor = c.trendUp ? colors.emerald : colors.blue;
    const trendWidth = doc.fontSize(7).font('Helvetica-Bold').widthOfString(c.trend) + 12;
    doc.roundedRect(x + cardWidth - trendWidth - 10, y + cardHeight - 24, trendWidth, 15, 7).fill(trendBg);
    doc.fontSize(7).font('Helvetica-Bold').fillColor(trendColor).text(c.trend, x + cardWidth - trendWidth - 4, y + cardHeight - 20, { width: trendWidth - 4, align: 'center' });
  });
  currentY += Math.ceil(cards.length / cardCols) * (cardHeight + cardGap) + 15;

  // ─── Breakdown sections (mirror the drawer's 4 chart cards) ───
  const renderBreakdown = (title: string, data: { label: string; count: number }[]) => {
    currentY = addSectionTitle(title, currentY, 18);
    const cardTop = currentY;
    const total = data.reduce((s, d) => s + d.count, 0);
    const rowsHeight = data.length === 0 ? 30 : data.length * 20 + 10;
    if (cardTop + rowsHeight > doc.page.height - 60) { doc.addPage(); currentY = 40; }
    const boxY = currentY;
    doc.roundedRect(margin, boxY, contentWidth, rowsHeight, 10).fillAndStroke(colors.white, colors.border);

    if (data.length === 0) {
      doc.fontSize(9).font('Helvetica').fillColor(colors.light).text('No data for this range yet.', margin + 15, boxY + 12);
    } else {
      const max = Math.max(...data.map((d) => d.count), 1);
      const barMaxWidth = contentWidth - 260;
      data.forEach((d, i) => {
        const rowY = boxY + 12 + i * 20;
        const color = SNAPSHOT_CHART_COLORS[i % SNAPSHOT_CHART_COLORS.length];
        doc.circle(margin + 18, rowY + 5, 4).fill(color);
        doc.fontSize(9).font('Helvetica').fillColor(colors.secondary).text(d.label, margin + 30, rowY, { width: 150 });
        const barWidth = total > 0 ? Math.max(2, (d.count / max) * barMaxWidth) : 2;
        doc.roundedRect(margin + 185, rowY + 1, barMaxWidth, 9, 3).fill(colors.bg);
        doc.roundedRect(margin + 185, rowY + 1, barWidth, 9, 3).fill(color);
        doc.fontSize(9).font('Helvetica-Bold').fillColor(colors.secondary).text(String(d.count), margin + 185 + barMaxWidth + 10, rowY, { width: 40, align: 'right' });
      });
    }
    currentY = boxY + rowsHeight + 20;
  };

  renderBreakdown('Jobs by status', dashboard.jobsByStatus);
  renderBreakdown('Applications by status', dashboard.applicationsByStatus);
  renderBreakdown('Candidates by source', dashboard.candidatesBySource);
  renderBreakdown('Interviews by status', dashboard.interviewsByStatus);
}

export async function generateAnalyticsSnapshotPDF(
  snapshot: { period: string; snapshotAt: Date; data: AnalyticsDashboard },
  generatedBy: string,
  tenantId: string | null,
): Promise<Buffer> {
  const timezone = await resolveTenantTimezone(tenantId);

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, bufferPages: true, size: 'A4' });
      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      renderAnalyticsSnapshotReport(doc, snapshot.period, snapshot.snapshotAt, snapshot.data, generatedBy, timezone);

      // ─── Footer (same template as the interview report) ───
      const pageWidth = doc.page.width;
      const margin = 50;
      const contentWidth = pageWidth - margin * 2;
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        doc.rect(0, doc.page.height - 40, pageWidth, 40).fill('#f8fafc');
        doc.moveTo(0, doc.page.height - 40).lineTo(pageWidth, doc.page.height - 40).strokeColor('#e2e8f0').lineWidth(1).stroke();
        const footerText = `Page ${i + 1} of ${range.count}  |  Generated securely by AgnoHire`;
        const fWidth = doc.fontSize(9).font('Helvetica').widthOfString(footerText);
        const fX = margin + (contentWidth - fWidth) / 2;
        doc.fillColor('#64748b').text(footerText, fX, doc.page.height - 25, { lineBreak: false });
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Usage Monitor PDF exports (AI Token Usage / Candidate Storage tabs)
// ─────────────────────────────────────────────────────────────────────────────

function usdFmt(n: number): string {
  return n < 0.01 && n > 0 ? `$${n.toFixed(4)}` : `$${n.toFixed(2)}`;
}

function tokensFmt(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return String(n);
}

function bytesFmt(bytes: number): string {
  if (!bytes) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.min(units.length - 1, Math.floor(Math.log(bytes) / Math.log(1024)));
  return `${(bytes / 1024 ** i).toFixed(i === 0 ? 0 : 1)} ${units[i]}`;
}

const USAGE_COLORS = {
  primary: '#0f172a',
  secondary: '#1e293b',
  text: '#475569',
  light: '#64748b',
  muted: '#94a3b8',
  border: '#e2e8f0',
  bg: '#f8fafc',
  white: '#ffffff',
};

/** Draws the shared AgnoHire report header used by both usage reports. */
function drawUsageReportHeader(
  doc: PDFKit.PDFDocument,
  title: string,
  subtitle: string,
  generatedBy: string,
  timezone: string,
): void {
  const pageWidth = doc.page.width;
  const margin = 40;
  doc.rect(0, 0, pageWidth, 120).fill(USAGE_COLORS.primary);
  doc.fontSize(32).font('Helvetica-Bold').fillColor(USAGE_COLORS.white).text('AgnoHire', margin, 40);
  doc.fontSize(14).font('Helvetica').fillColor(USAGE_COLORS.muted).text(title, margin, 75);
  doc.fontSize(10).font('Helvetica').fillColor(USAGE_COLORS.muted).text(`Generated by: ${generatedBy}`, margin, 95);

  const rightTextX = pageWidth - margin - 200;
  const generatedStr = new Date().toLocaleString('en-GB', { timeZone: timezone });
  doc.fontSize(10).font('Helvetica').fillColor(USAGE_COLORS.muted).text('Confidential', rightTextX, 40, { width: 200, align: 'right' });
  doc.fontSize(9).text(`Exported: ${generatedStr}`, rightTextX, 58, { width: 200, align: 'right' });
  doc.fontSize(9).text(subtitle, rightTextX, 71, { width: 200, align: 'right' });
}

/** Draws the shared AgnoHire report footer (page numbers) across every buffered page. */
function drawUsageReportFooter(doc: PDFKit.PDFDocument): void {
  const pageWidth = doc.page.width;
  const margin = 50;
  const contentWidth = pageWidth - margin * 2;
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.rect(0, doc.page.height - 40, pageWidth, 40).fill('#f8fafc');
    doc.moveTo(0, doc.page.height - 40).lineTo(pageWidth, doc.page.height - 40).strokeColor('#e2e8f0').lineWidth(1).stroke();
    const footerText = `Page ${i + 1} of ${range.count}  |  Generated securely by AgnoHire`;
    const fWidth = doc.fontSize(9).font('Helvetica').widthOfString(footerText);
    const fX = margin + (contentWidth - fWidth) / 2;
    doc.fillColor('#64748b').text(footerText, fX, doc.page.height - 25, { lineBreak: false });
  }
}

/** Draws a row of KPI cards (label/value/sub), wrapping to further rows as needed. */
function drawUsageKpiCards(
  doc: PDFKit.PDFDocument,
  cards: { label: string; value: string; sub?: string }[],
  startY: number,
): number {
  const margin = 40;
  const contentWidth = doc.page.width - margin * 2;
  const cardGap = 10;
  const cardCols = 4;
  const cardWidth = (contentWidth - cardGap * (cardCols - 1)) / cardCols;
  const cardHeight = 64;
  cards.forEach((c, i) => {
    const col = i % cardCols;
    const row = Math.floor(i / cardCols);
    const x = margin + col * (cardWidth + cardGap);
    const y = startY + row * (cardHeight + cardGap);
    doc.roundedRect(x, y, cardWidth, cardHeight, 10).fillAndStroke(USAGE_COLORS.white, USAGE_COLORS.border);
    doc.fontSize(8).font('Helvetica-Bold').fillColor(USAGE_COLORS.light).text(c.label.toUpperCase(), x + 12, y + 10, { width: cardWidth - 24 });
    doc.fontSize(16).font('Helvetica-Bold').fillColor(USAGE_COLORS.primary).text(c.value, x + 12, y + 26, { width: cardWidth - 24 });
    if (c.sub) doc.fontSize(8).font('Helvetica').fillColor(USAGE_COLORS.light).text(c.sub, x + 12, y + 46, { width: cardWidth - 24 });
  });
  return startY + Math.ceil(cards.length / cardCols) * (cardHeight + cardGap) + 15;
}

/** Draws a simple bordered table with a header row, wrapping to new pages as needed. */
function drawUsageTable(
  doc: PDFKit.PDFDocument,
  title: string,
  columns: { label: string; width: number; align?: 'left' | 'right' }[],
  rows: string[][],
  startY: number,
): number {
  const margin = 40;
  let y = startY;
  if (y > doc.page.height - 140) { doc.addPage(); y = 40; }
  doc.fontSize(14).font('Helvetica-Bold').fillColor(USAGE_COLORS.primary).text(title, margin, y);
  y += 22;

  const drawHeader = () => {
    doc.roundedRect(margin, y, columns.reduce((s, c) => s + c.width, 0), 22, 4).fill(USAGE_COLORS.bg);
    let cx = margin;
    doc.fontSize(9).font('Helvetica-Bold').fillColor(USAGE_COLORS.secondary);
    columns.forEach((c) => {
      doc.text(c.label, cx + 8, y + 6, { width: c.width - 12, align: c.align ?? 'left' });
      cx += c.width;
    });
    y += 26;
  };

  drawHeader();

  if (rows.length === 0) {
    doc.fontSize(9).font('Helvetica').fillColor(USAGE_COLORS.light).text('No data for this range yet.', margin + 8, y);
    return y + 24;
  }

  rows.forEach((row) => {
    doc.fontSize(9).font('Helvetica');
    const rowHeight = Math.max(
      14,
      ...columns.map((c, i) => doc.heightOfString(row[i] ?? '', { width: c.width - 12, lineGap: 1 })),
    ) + 8;

    if (y + rowHeight > doc.page.height - 60) {
      doc.addPage();
      y = 40;
      drawHeader();
    }

    let cx = margin;
    doc.fontSize(9).font('Helvetica').fillColor(USAGE_COLORS.text);
    columns.forEach((c, i) => {
      doc.text(row[i] ?? '', cx + 8, y, { width: c.width - 12, align: c.align ?? 'left', lineGap: 1 });
      cx += c.width;
    });
    doc.moveTo(margin, y + rowHeight).lineTo(margin + columns.reduce((s, c) => s + c.width, 0), y + rowHeight).strokeColor(USAGE_COLORS.border).lineWidth(0.5).stroke();
    y += rowHeight + 4;
  });

  return y + 20;
}

/** AI token usage report — mirrors the Usage Monitor "AI Token Usage" tab. */
export async function generateAiUsagePDF(
  data: {
    summary: UsageSummary;
    byTenant: UsageByTenant[];
    byFeature: UsageByFeature[];
    byModel: UsageByModel[];
  },
  days: number,
  generatedBy: string,
): Promise<{ buffer: Buffer; filename: string }> {
  const timezone = await resolveTenantTimezone(null);
  const { summary, byTenant, byFeature, byModel } = data;

  const buffer = await new Promise<Buffer>((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40, bufferPages: true, size: 'A4' });
      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      drawUsageReportHeader(doc, 'AI Token Usage Report', `Last ${days} days`, generatedBy, timezone);

      let y = drawUsageKpiCards(
        doc,
        [
          { label: 'Total Calls', value: String(summary.totalCalls), sub: `${summary.successRate}% success` },
          { label: 'Total Tokens', value: tokensFmt(summary.totalTokens), sub: `${tokensFmt(summary.promptTokens)} in / ${tokensFmt(summary.completionTokens)} out` },
          { label: 'Total Cost (est.)', value: usdFmt(summary.totalCostUsd), sub: summary.unpricedCalls ? `${summary.unpricedCalls} calls unpriced` : 'All models priced' },
          { label: 'Billable to Tenants', value: usdFmt(summary.billableCostUsd), sub: 'Platform-key usage, this range' },
        ],
        145,
      );

      y = drawUsageTable(
        doc,
        'Cost by workspace',
        [
          { label: 'Workspace', width: 175 },
          { label: 'Key', width: 75 },
          { label: 'Calls', width: 55, align: 'right' },
          { label: 'Tokens', width: 70, align: 'right' },
          { label: 'Total Cost', width: 75, align: 'right' },
          { label: 'Billable', width: 65, align: 'right' },
        ],
        byTenant.map((t) => [
          `${t.tenantName} (${t.tenantSlug})`,
          t.usesPlatformKey ? 'Platform' : 'Own key',
          String(t.calls),
          tokensFmt(t.totalTokens),
          usdFmt(t.totalCostUsd),
          t.billableCostUsd > 0 ? usdFmt(t.billableCostUsd) : '—',
        ]),
        y,
      );

      y = drawUsageTable(
        doc,
        'Cost by feature',
        [
          { label: 'Feature', width: 220 },
          { label: 'Calls', width: 75, align: 'right' },
          { label: 'Tokens', width: 100, align: 'right' },
          { label: 'Total Cost', width: 120, align: 'right' },
        ],
        byFeature.map((f) => [f.feature, String(f.calls), tokensFmt(f.totalTokens), usdFmt(f.totalCostUsd)]),
        y,
      );

      drawUsageTable(
        doc,
        'Cost by provider / model',
        [
          { label: 'Model', width: 160 },
          { label: 'Provider', width: 100 },
          { label: 'Tokens', width: 90, align: 'right' },
          { label: 'Total Cost', width: 90, align: 'right' },
          { label: 'Failed', width: 75, align: 'right' },
        ],
        byModel.map((m) => [m.model, m.provider, tokensFmt(m.totalTokens), usdFmt(m.totalCostUsd), m.failedCalls > 0 ? String(m.failedCalls) : '—']),
        y,
      );

      drawUsageReportFooter(doc);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });

  const dateStr = new Date().toISOString().split('T')[0];
  return { buffer, filename: `AI_Token_Usage_Report_${dateStr}.pdf` };
}

/** Candidate storage report — mirrors the Usage Monitor "Candidate Storage" tab. */
export async function generateStorageUsagePDF(
  data: { summary: PlatformStorageSummary; byTenant: TenantStorageBreakdown[] },
  generatedBy: string,
): Promise<{ buffer: Buffer; filename: string }> {
  const timezone = await resolveTenantTimezone(null);
  const { summary, byTenant } = data;

  const buffer = await new Promise<Buffer>((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40, bufferPages: true, size: 'A4' });
      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      drawUsageReportHeader(doc, 'Candidate Storage Report', `${summary.tenantCount} workspaces`, generatedBy, timezone);

      let y = drawUsageKpiCards(
        doc,
        [
          { label: 'Total Storage', value: bytesFmt(summary.totalBytes), sub: `${summary.tenantCount} workspaces` },
          { label: 'Resumes', value: bytesFmt(summary.resumeBytes) },
          { label: 'Proctoring Snapshots', value: bytesFmt(summary.proctorShotBytes + summary.assessmentProctorShotBytes), sub: 'Interviews + assessments' },
          { label: 'Attachments + Biometric', value: bytesFmt(summary.attachmentBytes + summary.biometricBytes) },
        ],
        145,
      );

      if (summary.unattributedBytes) {
        doc.fontSize(8).font('Helvetica').fillColor(USAGE_COLORS.light).text(
          `${bytesFmt(summary.unattributedBytes)} of storage belongs to no workspace (orphaned rows) — included in the total above but not in the table below.`,
          40,
          y,
          { width: doc.page.width - 80 },
        );
        y += 20;
      }

      drawUsageTable(
        doc,
        'Storage by workspace',
        [
          { label: 'Workspace', width: 125 },
          { label: 'Candidates', width: 65, align: 'right' },
          { label: 'Resumes', width: 65, align: 'right' },
          { label: 'Attachments', width: 80, align: 'right' },
          { label: 'Proctoring', width: 60, align: 'right' },
          { label: 'Biometric', width: 60, align: 'right' },
          { label: 'Total', width: 60, align: 'right' },
        ],
        byTenant.map((t) => [
          `${t.tenantName} (${t.tenantSlug})`,
          String(t.candidateCount),
          bytesFmt(t.resumeBytes),
          bytesFmt(t.attachmentBytes),
          bytesFmt(t.proctorShotBytes + t.assessmentProctorShotBytes),
          bytesFmt(t.biometricBytes),
          bytesFmt(t.totalBytes),
        ]),
        y,
      );

      drawUsageReportFooter(doc);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });

  const dateStr = new Date().toISOString().split('T')[0];
  return { buffer, filename: `Candidate_Storage_Report_${dateStr}.pdf` };
}
